Feature/go to top button
filipedeschamps/tabnews.com.br pull request #1039
Opened 2022-11-30 11:12 UTC by montoyaaa

Adiciona um simples botão ao scrollar para baixo no tabnews, para retornar ao topo. Senti falta de um ao navegar em conteúdos com muitas repostas pricipalmente.

2022-11-30 12:31 UTC, aprendendofelipe commented
Eu gostei, mas no meu celular ficou bugado. Nessa página abaixo ele não volta para o topo:

https://tabnews-eyz7izhpr-tabnews.vercel.app/Gustavo33/teste4593832181797422292334945798549354624941348715825899669

E a mudança adicionou um comportamento não desejado, que é voltar para o topo em toda navegação. O ideal é manter o scroll quando voltamos para a página anterior.

2022-11-30 12:44 UTC, montoyaaa commented
> Eu gostei, mas no meu celular ficou bugado. Nessa página abaixo ele não volta para o topo:
> 
> https://tabnews-eyz7izhpr-tabnews.vercel.app/Gustavo33/teste4593832181797422292334945798549354624941348715825899669
> 
> E a mudança adicionou um comportamento não desejado, que é voltar para o topo em toda navegação. O ideal é manter o scroll quando voltamos para a página anterior.

Show, Felipe. Vou validar esses pontos e em breve atualizo a branch.

2022-11-30 23:27 UTC, montoyaaa commented
> Eu gostei, mas no meu celular ficou bugado. Nessa página abaixo ele não volta para o topo:
> 
> https://tabnews-eyz7izhpr-tabnews.vercel.app/Gustavo33/teste4593832181797422292334945798549354624941348715825899669
> 
> E a mudança adicionou um comportamento não desejado, que é voltar para o topo em toda navegação. O ideal é manter o scroll quando voltamos para a página anterior.

Fala Felipe. No unmount do componente removi a estilização que causava a impressão de scrollar pra cima. Já sobre o bug no mobile, não consegui reproduzir localmente igual mostrado no preview do Vercel, sabe se pode ter algo interferindo?

2022-12-01 00:46 UTC, montoyaaa commented
> > Eu gostei, mas no meu celular ficou bugado. Nessa página abaixo ele não volta para o topo:
> > https://tabnews-eyz7izhpr-tabnews.vercel.app/Gustavo33/teste4593832181797422292334945798549354624941348715825899669
> > E a mudança adicionou um comportamento não desejado, que é voltar para o topo em toda navegação. O ideal é manter o scroll quando voltamos para a página anterior.
> 
> Show, Felipe. Vou validar esses pontos e em breve atualizo a branch.

Fala Felipe. No unmount do componente removi a estilização. Já sobre o bug no mobile, na verdade ele acompanha os limites da página. Como o layout quebra com conteúdo muito largo, ele sai dos limites do zoom que o navegador coloca. E ajustar apenas o layout não resolveria o problema de quando clicar ele nao ir até o topo (na verdade ele vai, mas por conta do zoom, parece que não). Faça o teste no seu celular, use os gestos de pinça com os dedos para dar zoom-out e analisar a página. Tens alguma ideia do que pode ser feito para contornar, já que esse é o resultado "certo"?

2022-12-01 22:59 UTC, montoyaaa commented
@aprendendofelipe \o

2022-12-27 03:38 UTC, montoyaaa commented on pages/interface/components/GoToTopButton/index.js
> +    window.addEventListener('scroll', onScroll, { passive: true });
Na verdade eu não conhecia o IntersectionObserver, muito obrigado por me apresentar. Implementei ele, se tiver algum pontinho sobre, só dar um grito. :)

2022-12-27 11:48 UTC, aprendendofelipe requested changes
Show @montoyaaa, mas quebrou porque você está buscando um elemento que não está presente no documento.

E como está praticamente pronto, após essa correção, você consegue unificar todos commits e seguir o padrão de mensagens em inglês?

Obrigado! 🤝

2022-12-27 11:48 UTC, aprendendofelipe commented on pages/interface/components/GoToTopButton/index.js
> +    const target = document.querySelector('#__next > div > div.Header-sc-11fu6rh-0.hunLgK');
Precisa buscar algo que você possa garantir que exista no documento.

Algo que você mesmo tenha adicionado no Header (ID ou class).

Também é bom usar um nome de variável que deixe mais claro qual é o elemento alvo.

2022-12-28 03:03 UTC, montoyaaa commented on pages/interface/components/GoToTopButton/index.js
> +    const target = document.querySelector('#__next > div > div.Header-sc-11fu6rh-0.hunLgK');
Pois é, ia falar isso. Acabei esquecendo de deixar o seletor daquele jeito haha. Se tiver mais algum pontinho ou observação que eu poderia melhor, só dar um toque. Abs

2023-01-03 12:11 UTC, aprendendofelipe approved these changes

2023-01-03 12:14 UTC, merged

2023-01-03 12:18 UTC, aprendendofelipe commented
Foi para produção 🚀