feat(tab-coin-buttons): add hover to improve user experience
filipedeschamps/tabnews.com.br pull request #1277
Opened 2023-02-27 12:28 UTC by PauloIVM

Olá!

Motivação da PR: Recentemente comecei a usar o tabnews. Como sou preguiçoso, não li muito sobre o funcionamento das tabcoins e etc. Quando vi os botões de arrow-up e arrow-down pra adicionar ou debitar tab-coins, eu realmente não entendi pra que serviam esses botões... de imediato eu nem achei que eram botões, achei que eram só uma questão de estilização. Depois que passei o mouse em cima sem querer, achei que seria algo relacionado à minimizar ou maximizar os comentários. Daí só depois que fui ler certinho o essa [postagem](https://www.tabnews.com.br/filipedeschamps/tentando-construir-um-pedaco-de-internet-mais-massa) do Filipe é que fui entender do que se tratava.

Acredito que adicionando um simples tooltip já melhore muito a experiência do usuário. E foi isso que eu fiz nessa PR. Seguem prints de como ficou:

![image](https://user-images.githubusercontent.com/59659732/221563703-23e8516d-92e6-4991-a91d-0bb375ffe6fe.png)

![image](https://user-images.githubusercontent.com/59659732/221563842-9f3afca1-885b-4575-8590-2348de27232e.png)

2023-02-27 13:05 UTC, Ryannnkl approved these changes

2023-02-28 00:54 UTC, Caixetadev submitted a review, later dismissed

2023-03-01 20:18 UTC, aprendendofelipe commented
Boa @PauloIVM, obrigado pelo PR!

Isso irá ajudar aos usuários novos. Mas estou em dúvida se não existe mensagem ainda mais explicativa do que creditar e debitar TabCoins, pois isso também pode não fazer sentido para quem ainda não entendeu a mecânica do TabNews.

O que acham? Alguém tem outra sugestão de mensagem?

2023-03-01 20:24 UTC, PauloIVM commented
@aprendendofelipe boa! Faz sentido. Algumas sugestões:

- "massinha" vs "não massinha";
- "conteúdo massinha" vs "conteúdo não massinha";
- "relevante" vs "irrelevante";
- "gostei" vs "não gostei";
- "dar tabcoins" vs "retirar tabcoins";

Achou algum desses legal?

2023-03-01 21:37 UTC, aprendendofelipe commented
> Achou algum desses legal?

Achei interessantes, mas não bateria o martelo em nenhum deles por enquanto. Vamos aguardar outras sugestões?

2023-03-02 11:46 UTC, Rafatcb commented
Acho que o Stack Overflow tem um bom texto no tooltip para votação nas perguntas que podemos levar como referência (não precisa ser uma única palavra, por exemplo):

| Tipo | Voto positivo | Voto negativo |
| --- | --- | --- |
| **Pergunta** | ![Positivo: "Esta pergunta mostra esforço de pesquisa; é útil e clara"](https://i.imgur.com/AwJftUa.png) | ![Negativo: "Esta pergunta não mostra nenhum esforço de pesquisa; ela não é clara ou não é útil"](https://i.imgur.com/qYS7ZyK.png) |
| **Resposta** | ![Positivo: "Esta resposta é útil"](https://i.imgur.com/ZktSJdc.png) | ![Negativo: "Esta resposta não é útil"](https://i.imgur.com/4RH3gKL.png) |

Lembrando que essa tooltip não "resolve problemas", apenas ameniza. Quem está num dispositivo touch provavelmente não a verá, e quem está usando mouse/touchpad talvez clique antes de vê-la aparecendo. A documentação da [Tooltip no Primer](https://primer.style/react/Tooltip) fala mais sobre isso:

> Tooltips as a UI pattern should be our last resort for conveying information because it is hidden by default and often with zero or little visual indicator of its existence.
> Before adding a tooltip, please consider: Is this information essential and necessary? Can the UI be made clearer? Can the information be shown on the page by default? See [Tooltip alternatives](https://primer.style/design/accessibility/tooltip-alternatives) for more accessible alternatives.

2023-03-02 12:05 UTC, PauloIVM commented
@Rafatcb boa! Achei legal a ideia de se basear no stack-overflow. Fica bem mais claro mesmo.

2023-03-12 19:53 UTC, ermesonqueiroz commented
Também pode ser usado como referência os Termos de Uso [atuais](https://www.tabnews.com.br/termos-de-uso) do Tabnews e o que ainda está em discussão em #1153

2023-03-12 20:35 UTC, aprendendofelipe commented
Considerando o que o @Rafatcb falou, que não precisa ser uma palavra única, e utilizando nomenclatura já adotada no TabNews, que qual?

* "Achei relevante"
* "Não achei relevante"

É algo que vai funcionar bem tanto para conteúdos, perguntas, respostas etc. E mesmo um novo usuário vai entender.

2023-03-12 20:40 UTC, ermesonqueiroz commented
Acho bom e objetivo.

2023-03-14 07:00 UTC, PauloIVM commented
Beleza! Vou subir um commit alterando

2023-03-14 07:10 UTC, PauloIVM commented
@aprendendofelipe alterado :+1:

2023-03-14 11:58 UTC, aprendendofelipe requested changes
Boa @PauloIVM, falta resolver os conflitos de merge, e para isso eu anotei no código o que deve ser corrigido, mas também precisa adicionar `const isInAction = isPosting || isAnimatingCredit || isAnimatingDebit;` conforme está no PR #1255 

Fora isso, só adicionei a sugestão de remover o `noDelay` para o `Tooltip` não se tornar incoveniente.

2023-03-14 11:58 UTC, aprendendofelipe commented on pages/interface/components/TabCoinButtons/index.js
> +      </Tooltip>
```suggestion
      <Tooltip aria-label="Achei relevante" direction="ne">
        <IconButton
          variant="invisible"
          aria-label="Creditar TabCoin"
          icon={ChevronUpIcon}
          size="small"
          sx={{ color: 'fg.subtle', lineHeight: '18px' }}
          onClick={() => transactTabCoin('credit')}
          disabled={isInAction}
        />
      </Tooltip>
```

1. Remover o `<Box>` desnecessário;
2. Atualizar para as novas versões de `onClick` e `disable`;
3. Sugiro a remoção do `noDelay={true}`;
4. Fazer o mesmo com o botão de débito.

2023-03-14 13:55 UTC, B-Schmitz commented
Validaram se direction: "ne" fica visível no mobile?

2023-03-16 14:34 UTC, PauloIVM commented
Boa! Já vou subir essas alterações! Desculpem a demora pra responder hehe.

2023-03-16 14:50 UTC, PauloIVM commented
@aprendendofelipe alterações feitas:

![image](https://user-images.githubusercontent.com/59659732/225655058-725586bf-5fc1-4eac-a2c6-902f3bbc00d4.png)

2023-03-16 15:48 UTC, merged

2023-03-30 00:06 UTC, aprendendofelipe commented
@PauloIVM você foi citado no post comemorativo 🎉

https://www.tabnews.com.br/FelipeBarso/tabnews-dark-mode-e-novas-funcionalidades-do-editor