Feat(Header): Makes the header appear when scroll upwards
filipedeschamps/tabnews.com.br pull request #1295
Opened 2023-03-02 23:00 UTC by emanuelfranklyn

Esse pull request é baseado na discussão: #1225

Header: Agora o header aparece em tela quando o usuário sobe a tela, deixando a tela limpa quando descendo a página e em vista para melhor acesso ao subir, similar ao que navegadores mobile fazem com a barra de URL.

Em vista disso foi necessário modificar o funcionamento do `GoToTopButton`:

GoToTopButton: Agora o botão aparece quando o usuário não está no topo da tela ao invés de somente quando o header não estiver mais visível.

As alterações foram testadas no navegador firefox 110.0.1 (64-bits) e no modo simulação de dispositivo mobile em diversas resoluções

2023-03-06 20:52 UTC, aprendendofelipe requested changes
@emanuelfranklyn, obrigado pelo PR! 💪

Eu gostei bastante do resultado. Mas vamos ver o que o pessoal achou. 👍

Enquanto isso, veja os comentários que eu fiz no código e, após as adequações, rode `npm run lint:fix` e também corrija a mensagem de commit, pois se não passar nas verificações não tem como fazer merge. 🤝

2023-03-06 20:52 UTC, aprendendofelipe commented on pages/interface/components/Header/index.js
> +  const [showHeader, setShowHeader] = useState(0);
Será que esse nome de variável está representando bem o que está sendo armazenado nela?

Está me remetendo a um booleano, mas o que está sendo armazenada é a posição vertical do `Header`.

2023-03-09 11:24 UTC, emanuelfranklyn commented
Fiz as correções solicitadas, porem, não sei se o teste do nome do commit vai considerar esse ultimo ou o do pull request original

2023-03-09 13:56 UTC, aprendendofelipe commented
> Fiz as correções solicitadas, porem, não sei se o teste do nome do commit vai considerar esse ultimo ou o do pull request original

Olá @emanuelfranklyn, todos os commits são considerados, não apenas o último, então é preciso corrigir a mensagem dos [commits](https://github.com/filipedeschamps/tabnews.com.br/pull/1295/commits) anteriores. Tem diversas maneiras de se fazer isso, e eu sugiro já unificar os commits nesse processo (squash), mas em qualquer uma delas, após a correção, você vai precisar fazer um push forçado (`git push -f`) para subir aqui no GitHub.

-----

Sobre a feature, eu acho bem melhor do que a sugestão anterior de fixar o header.

A única coisa que eu tentaria mudar é o movimento do header pare ele ficar mais natural, fazendo sumir ou aparecer no mesmo ritmo do scroll.

Então seria legal aproveitar esse tempo que estamos deixando para a Turma avaliar a funcionalidade para ver se é possível melhorar esse movimento. 🤝

2023-03-12 02:34 UTC, emanuelfranklyn commented
Acho que uma alteração a ser feita e adicionar uma velocidade de scroll para o trigger, já que as vezes no mobile quando escrolando bem devagar a tela acaba detectando que vc subiu (pode ser so bug do meu celular mesmo, se alguem puder confirmar agradeço) para só mostrar o header se a quantia total do scroll foi maior que x pixeis (x poderia ser a altura do elemento header em si),  e se for menor esconde a barra de header, pois provaveomente foi um scroll up por engano ou bug do touch

2023-03-12 03:16 UTC, aprendendofelipe commented
@emanuelfranklyn, será que não fica legal se, enquanto o `header` estiver visível, fazer o valor de `top` variar exatamente a mesma quantia de scroll?

Pelo que entendi da sua implementação ele varia entre 0 e -64px, mas não assume os valores intermediários. É isso, né? 

Por exemplo, se eu rolar só 30px, o `top` poderia receber -30px ao invés de ir direto para 64px. O que acha?

2023-03-12 03:22 UTC, emanuelfranklyn commented
É uma opção valida, porem tem que adicionar que se o usuario parar o scroll no meio ele arredonde para o estado mais proximo, para evitar do menu ficar parado cortado ao meio da tela, e ai renover a transition para que ela apareça junto ao scroll do usuario

2023-03-12 03:27 UTC, aprendendofelipe commented
Do jeito que eu falei, o header vai parar no meio se o usuário só rolar um pouco, mas não vejo problema, pois o movimento deve ser mais natural.

O que você sugeriu agora é continuar indo diretamente de 0 para -64 e vice-versa. Mas minha sugestão é deixar assumir os valores de acordo com o scroll.

2023-03-12 13:01 UTC, emanuelfranklyn commented
Na vdd o que eu quis dizer é que o quando o usuario arrastar para cima ele vai ver o header aparecendo naturalmente e quando ele soltar o dedo da tela ai ele arredonda a posição entre visivel e não visivel, mas enquanto o dedo estiver na tela ele faz o scroll natural do header, que é a forma que os browsers mobile fazem com a narra de url

2023-03-12 22:37 UTC, rodrigoKulb commented
Curti o resultado no preview https://tabnews-git-fork-emanuelfranklyn-main-tabnews.vercel.app/sowlfie/programacao-de-robotica-ideias-criativas-para-controlar-maquinas-via-codigo

2023-03-19 00:07 UTC, emanuelfranklyn commented
Como mencionado adicionei scroll natural, onde se você escrollar 30px o header só aparece 30px (até que você pare o scroll aí ele arredonda para evitar situações onde o header fica preso na tela cortado pela metade, o que é um incômodo caso você queira usar ele ou não), também adicionei um sistema de threshold visto que em dispositivos moveis é comum você acabar fazendo scroll de 1 ou 2 pixeis quando tira o dedo da tela e isso acaba dando trigger para o header aparecer o que podia acabar incomodando, a forma que funciona é se você tiver descendo a tela e descer mais que 5px de uma vez o header some, caso você esteja subindo a tela (ação que dá trigger para o header aparecer) caso suba mais que 5px o header aparece, respeitando a velocidade de scroll e caso você pare de scrollar arredonda a exibição para o estado ideal.

2023-10-06 20:23 UTC, aprendendofelipe commented
Acredito que isso ainda deveria ser implementado. E que bastariam pequenos ajustes no PR atual, mas vou fechar ele porque ficou desatualizado, além de não estar passando no CI, mas manterei a issue #1225 aberta até a definição da solução 🤝

2023-10-06 20:23 UTC, closed without merging