refactor(password input): use primer features
filipedeschamps/tabnews.com.br pull request #1304
Opened 2023-03-07 17:46 UTC by edersonlucas

Nesta PR estou apenas fazendo uma sugestão de refatoração no `componente` para usar recursos do `primer`.

2023-03-07 18:23 UTC, aprendendofelipe commented
@edersonlucas, obrigado pelo PR! 💪

A questão do tamanho do input parece ser resolvida só usando o `trailingVisual` no lugar do `trailingAction`. Ou sobra algo para consertar?

As demais alterações são só por causa da direção do tooltip ou tem outra motivação?

Se for só isso, acho melhor usar o `TextInput.Action` mesmo, pois ele já lida com diversas questões pra gente, como a acessibilidade.

Por exemplo, com ele nós conseguimos navegar até o `eye` com a tecla `Tab`.

E a questão da direção do tooltip parece que um PR bem simples no repositório do Primer e já resolve. 👍

2023-03-07 18:43 UTC, edersonlucas commented
@aprendendofelipe A questão do `trailingVisual` é só para o botão ficar mais bem posicionado e não tão no canto, mas como o `TextInput.Action` tem um `padding` não da para perceber.

As demais alterações era só devido à direção do `tooltip`, mas tem razão na questão da acessibilidade.

Fiz um teste aqui se a gente remover o `padding` do `TextInput.Action` o input volta ao tamanho normal e usando o `trailingVisual` conseguimos reposicionar ele. Forçarei um push aqui com essa alteração.

2023-03-07 20:48 UTC, edersonlucas commented
Dei uma inspecionada na página agora e acho que entendi oque acontece. O `trailingAction` cria uma tag `span` que engloba o `tooltip` e o `eye`, só que essa tag `span` tem um `margin: 4px`. Já quando passamos o `trailingVisual` ele cria outra `span` que engloba tudo com o `span` anterior, mas o `margin de 4px` fica só para `left` e `right`. Ele também adiciona ao `TextInputWrapper` um `padding rigth 12px` afastando assim o `eye` do canto.

2023-03-08 01:02 UTC, aprendendofelipe requested changes

2023-03-08 01:02 UTC, aprendendofelipe commented on pages/interface/components/PasswordInput/index.js
> +            sx={{ color: 'fg.subtle', padding: '0' }}
```suggestion
            sx={{ color: 'fg.subtle' }}
```

Não podemos deixar o padding zerado por questão de acessibilidade, pois a área clicável fica muito pequena.

2023-03-08 01:08 UTC, aprendendofelipe submitted a review, later dismissed

2023-03-08 01:18 UTC, edersonlucas commented on pages/interface/components/PasswordInput/index.js
> +            sx={{ color: 'fg.subtle', padding: '0' }}
Entendi, realmente não pensei nesse detalhe. Show! 🤝

2023-03-08 01:34 UTC, edersonlucas commented
@aprendendofelipe E se a gente deixa-se o `TextInput` `relativo` e o `eye` `absoluto` e ajusta-se o `right` e `top`.  Assim manteríamos os 2 inputs do mesmo tamanho e o `padding` do `eye` não faria diferença. O que você acha?

2023-03-08 01:47 UTC, aprendendofelipe commented
Acho que não estou entendendo de qual diferença de tamanho você está falando. O que está em produção está realmente com alturas diferentes, mas com o `trailingVisual` no lugar do `trailingAction`, pra mim ficou correto. Veja nesse link ou na imagem abaixo:

https://tabnews-git-fork-edersonlucas-refactor-component-537e78-tabnews.vercel.app/login

A borda está igual. Já a largura interna do input vai ficar diferente mesmo já que tem o botão do ícone ali.

![image](https://user-images.githubusercontent.com/77860630/223597331-b58dc98c-0f07-4d7e-837f-4317ec78532f.png)

2023-03-08 01:52 UTC, edersonlucas commented
Pois é estranho. Porque na imagem para mim está normal, mas acessando da minha máquina esse link fica diferente 🤔

![image](https://user-images.githubusercontent.com/27015559/223598713-6f1c0c57-c037-42e3-a6d2-5cc4dbdf2bc1.png)

2023-03-08 02:09 UTC, edersonlucas commented
Nestas imagens acredito que de para ver melhor, a diferença é só de `5px`. E no celular não vejo diferença alguma só no computador. 🤔

![Input 1](https://user-images.githubusercontent.com/27015559/223600893-40866dca-f19f-47f0-960f-d1b69d0afb38.png)
![Input 2](https://user-images.githubusercontent.com/27015559/223600907-967ab950-c3f2-4ad2-9514-aab93ef8ac87.png)

2023-03-08 03:14 UTC, b2evandro commented
> Agora consegui ver +1
> 
> A altura dos campos varia conforme o tamanho da janela, mas eles não estão mudando da mesma maneira, então dependendo do tamanho da janela ficam iguais ou não... Vamos precisar investigar

Tá melhor do que o que está em produção hoje, mas tem um diferença.
O que consegui notar debugando aqui, é que isso não é na span e sim **só no tamanho do input**. Esse tamanho é proveniente de algum flex que existe na pagina, agora saber qual?

![Gif de exemplo](https://user-images.githubusercontent.com/55710708/223610337-8040d4f7-b25f-46a9-8808-804f10964fdb.gif)

2023-03-08 03:18 UTC, aprendendofelipe commented
Passando `sx={{ height: ['51px', null, '43px'] }}` diretamente para o `TextInput` da senha parece que resolve, mas eu não gostei da ideia de fixar esse tamanho ou mesmo limitar ele com `maxHeight`, então uma alternativa é limitar o menor tamanho possível dos outros campos, então teria que passar `sx={{ minHeight: [null, null, '46px'] }}` para os `TextInput` de username e email na página de cadastro e de login.

Se achar a ideia válida é só mandar o commit 👍

2023-03-08 03:20 UTC, edersonlucas commented
@aprendendofelipe Boaa! Eu estava testando algo parecido. Cheguei nesse tamanho `sx={{ minHeight: '47px' }}`

2023-03-08 03:27 UTC, aprendendofelipe commented
> @aprendendofelipe Boaa! Eu estava testando algo parecido. Cheguei nesse tamanho `sx={{ minHeight: '47px' }}`

Verdade, no caso de `minHeight` não precisa passar um array, e basta passar o valor, mas pra mim o correto é `46px`.

2023-03-08 03:30 UTC, edersonlucas commented
`46px` ficou perfeito, vou subir aqui.

2023-03-08 03:40 UTC, aprendendofelipe approved these changes

2023-03-08 03:41 UTC, merged

2023-03-08 03:47 UTC, aprendendofelipe commented
Em produção 🚀🚀🚀