feat(add termo de uso): add link para o termo de uso na pagina de cadastro
filipedeschamps/tabnews.com.br pull request #1343
Opened 2023-03-24 11:47 UTC by jgbispo

Como um dos tópicos da issue #1140 e descrito na #1153, foram adicionados os termos de uso na página de cadastro.

2023-03-24 13:43 UTC, aprendendofelipe requested changes
Olá @jgbispo, obrigado pelo PR! 💪

Precisa de alguns ajustes que comentei no código 👍

2023-03-24 13:43 UTC, aprendendofelipe commented on pages/cadastro/index.public.js
> +              Ao criar uma conta, você estará concordando com os{' '}
Gostei da frase, mas gostaria de saber a opinião da Turma e, se for o caso, analisar outras alternativas.

2023-03-24 13:43 UTC, aprendendofelipe commented on pages/cadastro/index.public.js
> +              <Link href="/termos-de-uso" sx={{ color: '#2cb7c7' }} target="_blank">
Mesma coisa com relação à cor.

2023-03-24 13:43 UTC, aprendendofelipe commented on pages/cadastro/index.public.js
>  import { DefaultLayout, PasswordInput } from 'pages/interface/index.js';
```suggestion
import { DefaultLayout, Link, PasswordInput } from 'pages/interface/index.js';
```

Use o `Link` customizado

2023-03-24 13:43 UTC, aprendendofelipe commented on pages/cadastro/index.public.js
> +import { FormControl, Box, Heading, Button, TextInput, Flash, Link, Text } from '@primer/react';
```suggestion
import { FormControl, Box, Heading, Button, TextInput, Flash, Text } from '@primer/react';
```

2023-03-24 17:06 UTC, jgbispo commented on pages/cadastro/index.public.js
> +          <div style={{ textAlign: 'center', width: '100%' }}>
Nunca usei o Prime, vi por cima quando fui adicionar ao código, mas vou dar uma olhada e melhorá-lo.

2023-03-24 17:07 UTC, jgbispo commented on pages/cadastro/index.public.js
> +            <Text sx={{ fontWeight: 'bold', fontSize: '12px', color: '#a6a6a6' }}>
Vou olhar sobre as cores. Não sei se é a 12px o padrão, quando deixei sem definir a fontSize ficou, em minha opinião, grande para esse tipo de informação.

2023-03-25 00:52 UTC, aprendendofelipe commented on pages/cadastro/index.public.js
> +            <Text sx={{ fontWeight: 'bold', fontSize: '12px', color: '#a6a6a6' }}>
Ok, vou deixar como draft por enquanto. 🤝

2023-03-30 01:48 UTC, closed without merging