feat(add new content button): add new content button on header
filipedeschamps/tabnews.com.br pull request #1349
Opened 2023-03-28 05:31 UTC by victorhcb

#1238 

Vi essa issue aberta há um certo tempo e achei interessante tentar implementar algo nesse sentido.
Obs.: Ainda estou aprendendo como ajudar por aqui no projeto então peço desculpas se tiver feito algo errado.

2023-04-24 21:43 UTC, ajmeireles submitted a review, later dismissed

2023-04-28 21:54 UTC, laviodias commented
Oi, Victor.
Gostei da funcionalidade, então vou te sugerir de antemão que implemente uma versão responsiva. Da forma como está, o header quebra em telas menores. Também é preciso resolver o conflito existente entre as branches.
Também tenho um ponto que acho interessante de se considerar, mas não é uma sugestão, é apenas para você pensar sobre. Faz sentido manter a exibição do botão uma vez que o usuário já esteja na página de criar uma nova postagem?

Fico a disposição para discutir esse ponto, se quiser.

2023-04-28 22:49 UTC, aprendendofelipe commented
Olá @victorhcb, obrigado pelo PR! 💪

Me perdoe a demora em responder 😅

Ficou meio grande esse botão, né? Não acha que ficaria melhor um botão pequeno no estilo do GitHub?

![image](https://user-images.githubusercontent.com/77860630/235265291-967df7be-46ea-4b73-92b7-a57d932f3c4c.png)

Talvez usar o `IconButton` 👍

Ótimos pontos @laviodias! 💪 

Com relação a responsividade, com base nas conversas do #1279, eu acho que o botão vai precisar ficar oculto na versão mobile.

2023-05-04 05:43 UTC, Caixetadev approved these changes

2023-05-04 10:51 UTC, victorhcb commented
Show pessoal! Fiz algumas correções de acordo com o que foi passado...

> Ficou meio grande esse botão, né? Não acha que ficaria melhor um botão pequeno no estilo do GitHub?
> 
> ![image](https://user-images.githubusercontent.com/77860630/235265291-967df7be-46ea-4b73-92b7-a57d932f3c4c.png)
> 

Sobre isso, realmente acho que não caberia um botão com texto... fiz a alteração para o ícone simples, vejam o que acham...

![image](https://user-images.githubusercontent.com/85972147/236181867-ec6b3f96-e5c1-41b7-9987-920495e00176.png)


> Com relação a responsividade, com base nas conversas do #1279, eu acho que o botão vai precisar ficar oculto na versão mobile.

Em relação a responsividade, fiz alguns testes usando a dev tools aqui e não sei se a responsividade ficou prejudicada... acredito que o botão não tenha afetado tanto a responsividade. O único dispositivo no qual há um problema de responsividade pelo DevTools já apresenta problemas na versão atual do Header... será que não valeria a pena um PR corrigindo o Header para esse ponto específico?

Seguem algumas imagens:

Iphone 12 PRO
![image](https://user-images.githubusercontent.com/85972147/236182627-0c30073f-3324-47ed-ad9d-ed9d48ef5884.png)

Galaxy S20
![image](https://user-images.githubusercontent.com/85972147/236182695-1f57e670-bf34-4c1b-b539-d8307e4d9690.png)

> Oi, Victor. Gostei da funcionalidade, então vou te sugerir de antemão que implemente uma versão responsiva. Da forma como está, o header quebra em telas menores. Também é preciso resolver o conflito existente entre as branches. Também tenho um ponto que acho interessante de se considerar, mas não é uma sugestão, é apenas para você pensar sobre. Faz sentido manter a exibição do botão uma vez que o usuário já esteja na página de criar uma nova postagem?

Sobre o ponto de manter o botão mesmo na página de publicação, fiquei na dúvida se deveria mesmo alterar nesse PR já que o botão também permanece no ActionMenu já existente... o que vocês pensam em relação a isso?

2023-05-04 12:52 UTC, aprendendofelipe requested changes
Show @victorhcb! 💪

Sobre remover o ícone quando estiver na página de publicação, eu não acho necessário. 👍

Sobre o restante, por favor, veja meus comentários no código 🤝

2023-05-04 12:52 UTC, aprendendofelipe commented on pages/interface/components/Header/index.js
> +              mr: 2,
```suggestion
            sx={{
              display: ['none', 'flex'],
              mr: 2,
```

Conforme conversas que eu mencionei, é melhor não adicionar esse botão na versão mobile. E não vai ser legal adicionar e depois remover, então é melhor já não adicionar.

2023-05-04 12:52 UTC, aprendendofelipe commented on pages/interface/components/Header/index.js
> +              <HeaderLink href="/publicar" aria-label="Publicar novo conteúdo">
```suggestion
              <HeaderLink href="/publicar">
```

Estou em dúvida se precisamos mesmo duplicar o `aria-label` que já está presente no `Tooltip`?

2023-05-04 12:52 UTC, aprendendofelipe commented on pages/interface/components/Header/index.js
> +                <MdAdd size={20} color="white" />
```suggestion
                <PlusIcon size={16} />
```

Motivo: É o ícone oficial da biblioteca de UI do TabNews, então a estilização está mais coerente com o restante do header, por exemplo o alinhamento e o hover.

2023-05-05 04:26 UTC, aprendendofelipe approved these changes

2023-05-05 04:28 UTC, merged

2023-05-05 04:39 UTC, aprendendofelipe commented
Em produção! 🚀🚀🚀

@victorhcb, bem vindo à Turma de contribuidores do TabNews! 👏👏👏

2023-05-05 06:58 UTC, victorhcb commented
Aaaaah que massaaa!!!!
Estou muito feliz de começar a contribuir por aqui... e a ideia é tentar fazer cada vez mais contribuições pois agora estou tentando começar a pegar o jeito hahaha
Inclusive... me desculpe pelos probleminhas bestas de implementação... espero ter mais ajudado mais do que atrapalhado hahahaah  Inclusive... Sinto que acabei fazendo uma bagunça nos commits iniciais... isso não seria prejudicial?

vlwww por toda a ajuda :D

2023-05-05 12:41 UTC, fabiosvm commented
Bacana!

2023-06-01 02:02 UTC, aprendendofelipe commented
@victorhcb você foi citado no post comemorativo: 

https://www.tabnews.com.br/FelipeBarso/tabnews-novo-ranqueamento-otimizacoes-e-mais 🎉