refactor(authorization): use early return on can method
filipedeschamps/tabnews.com.br pull request #1427
Opened 2023-05-27 16:31 UTC by JoandersonPaiva

Uma sugestão de refatoração para o método `can`  que verifica se o usuário possui determinada feature,  em casos de edição de usuário além de validar se o usuário possui essa feature também valida se o usuário que está editando é o mesmo que está sendo editado, e em casos de edição de conteúdo valida se o usuário é o dono do conteúdo ou se possui a feature de editar conteúdo de terceiros. Rodei os testes antes e depois das alterações, todos os testes continuaram passando.
O objetivo da refatoração é  ajudar na legibilidade do código, foi umas das primeiras funções que parei para estudar no código e levei um tempinho para entender.

2023-05-27 20:22 UTC, aprendendofelipe reviewed
Boa @JoandersonPaiva, obrigado pelo PR! 💪

Realmente essa função não está simples de analisar qual será o retorno em qualquer caso.

E sua sugestão de usar *early return* parece ser uma ótima ideia para facilitar esse entendimento. 👍

Nessa linha, acha que a opção abaixo fica mais fácil de entender?

```js
function can(user, feature, resource) {
  validateUser(user);
  validateFeature(feature);

  if (!user.features.includes(feature)) return false;

  if (!resource) return true;

  if (feature === 'update:user') return user.id === resource.id

  if (feature === 'update:content') {
    return user.id === resource.owner_id || user.features.includes('update:content:others')
  }

  return true;
}

2023-05-27 22:25 UTC, JoandersonPaiva commented
> Boa @JoandersonPaiva, obrigado pelo PR! 💪
> 
> Realmente essa função não está simples de analisar qual será o retorno em qualquer caso.
> 
> E sua sugestão de usar _early return_ parece ser uma ótima ideia para facilitar esse entendimento. 👍
> 
> Nessa linha, acha que a opção abaixo fica mais fácil de entender?
> 
> ```js
> function can(user, feature, resource) {
>   validateUser(user);
>   validateFeature(feature);
> 
>   if (!user?.features?.includes(feature)) return false;
> 
>   if (!resource) return true;
> 
>   if (feature === 'update:user') return user.id === resource.id
> 
>   if (feature === 'update:content') {
>     return user.id === resource.owner_id || user.features.includes('update:content:others')
>   }
> 
>   return true;
> }
> ```

Olá @aprendendofelipe! Obrigado por responder minha sugestão!
Achei bem bacana sua sugestão, mas acho que seria bem interessante manter algumas variáveis para que fique mais claro o que tá sendo comparado e até mesmo retornado, acho que ajudaria a não travar muito pessoas que estão começando a colaborar com o projeto, o que é o meu caso, o que acha dessa sugestão: 
```js
function can(user, feature, resource) {
  validateUser(user);
  validateFeature(feature);
  const userHasFeature = user.features.includes(feature);

  if (!resource) return userHasFeature;
  if (feature === 'update:user' && userHasFeature) {
    const isCurrentUserEditingOwnProfile = user.id === resource.id;
    return isCurrentUserEditingOwnProfile;
  };

  if (feature === 'update:content') {
    const isUserUptatingOwnContent = user.id === resource.owner_id;
    const canUpdateContentFromOthers = user.features.includes('update:content:others');
    return (userHasFeature && isUserUptatingOwnContent) || canUpdateContentFromOthers;
  }

  return userHasFeature;
}
``` 
Abraços!

2023-05-27 23:48 UTC, aprendendofelipe commented
Intencionalmente, ou não, a sua versão modifica a lógica original, não é apenas uma refatoração. Você corrigiu a falha de não verificar se o usuário possui a *feature* `update:content` ao editar conteúdos próprios. 👍

Esse problema já existia antes nessa função para o caso da *feature* `update:user`, o que foi corrigido no PR #1312, mas acho que ninguém notou que o problema permaneceu para a edição de conteúdos. 😱

De fato essa função era confusa, e por isso existia um `TODO` nos lembrando de que uma hora precisávamos dar uma boa atenção a ela.

Aproveitando a sugestão de usar *early return*, a minha versão também muda a lógica e tenta evitar que esse problema se repita futuramente ao já retornar `false` de cara se o usuário não tiver a *feature* básica necessária. O restante só é verificado se o usuário possuir a *feature*, então não é necessário verificar novamente, eliminando a necessidade da variável. Além disso, sem a variável fica mais claro que o padrão no final da função é retornar `true`, algo que já ocorre na versão atual, mas que não fica tão óbvio ao usar uma variável, seja a `authorized` ou `userHasFeature`, e provavelmente isso ajudava a dificultar o entendimento dela.

Se formos usar a lógica da minha sugestão, acho melhor não criar essas variáveis extras, pois elas abstraem coisas que não deveríamos abstrair nessa função. Só eliminando elas é que me sento tranquilo em remover o `TODO` que existia ali.

Caso concorde, pode atualizar o PR.  🤝

Obs. Eu editei minha sugestão, pois não precisamos do encadeamento opcional, já que essa verificação é cumprida pela `validateUser`.

Abraços!

2023-05-28 01:01 UTC, JoandersonPaiva commented
show! concordo sim, entendendo melhor o contexto faz sentido não manter essas variáveis, apliquei a sua sugestão no código nesse [commit](https://github.com/filipedeschamps/tabnews.com.br/pull/1427/commits/e7234fa16a0ede3ad6215220890c90ba0c207ee3).
Fico feliz de ter contribuído na correção de uma falha, a principio fiz apenas refactor mas nesse [commit](https://github.com/filipedeschamps/tabnews.com.br/pull/1427/commits/b203ac325f40851919ff636af645bfdcd5f0b69b) apliquei as sugestões de um amigo que viu meu pr e verifiquei que os testes continuaram passando e então mantive essa validação extra, o que faz meu pr deixar de ser apenas um refactor haha.
Muito obrigado pelas sugestões, abraços!

2023-05-28 20:53 UTC, aprendendofelipe requested changes
@JoandersonPaiva, por favor, veja os dois novos comentários.

O padrão do retorno ser `true` nessa função não estava legal, então fiz outra sugestão em que o padrão passa a ser `false`.

2023-05-28 20:53 UTC, aprendendofelipe commented on models/authorization.js
> +  if (!user?.features?.includes(feature)) return false;
```suggestion
  if (!user.features.includes(feature)) return false;
```

Não precisa do encadeamento opcional, pois isso já é coberto pela função `validateUser`

2023-05-28 20:53 UTC, aprendendofelipe commented on models/authorization.js
> +  return true;
Esse retorno `true` como padrão estava me incomodando, então criei essa nova versão:

```js
function can(user, feature, resource) {
  validateUser(user);
  validateFeature(feature);

  if (!user.features.includes(feature)) return false;

  if (!resource) return true;

  switch (feature) {
    case 'update:user':
      return user.id === resource.id;

    case 'update:content':
      return user.id === resource.owner_id || user.features.includes('update:content:others');

    case 'create:content:text_root':
    case 'create:content:text_child':
      return true;
  }

  return false;
}

2023-05-28 21:55 UTC, JoandersonPaiva commented on models/authorization.js
> +  if (!user?.features?.includes(feature)) return false;
show, faz sentido! removido 🚀

2023-05-28 22:01 UTC, JoandersonPaiva commented
@aprendendofelipe caraca, curti bastante 😍 ! notei que por conta da mudança do default para false agora tbm deixamos a validação de criação de conteúdo mais explicita, já fiz a alteração sugerida, inclui o retorno de false como default para a expressão do switch case, o que acha?

2023-05-28 22:07 UTC, JoandersonPaiva commented on models/authorization.js
> +  return true;
show! apliquei as sugestões! fiz uma micro mudança que comentei na thread 🚀

2023-05-28 23:06 UTC, aprendendofelipe commented
> tbm deixamos a validação de criação de conteúdo mais explicita

Exatamente! Acho que agora sim está bem explícito tudo que essa função faz. Ficou muito melhor! 🤝

> inclui o retorno de false como default para a expressão do switch case, o que acha?

Não muda nada na lógica, mas acho que fica um pouco mais fácil de entender a função `can` se existir um retorno padrão no final dela, e isso elimina a necessidade do retorno `default` na switch case. 👍

Caso saiba fazer isso, também seria legal unificar os commits do PR 🤝

2023-05-28 23:39 UTC, JoandersonPaiva commented
@aprendendofelipe boa! feito, removi o default e deixei o false sendo retornado ao fim  da função, tbm unifiquei meus commits deixando apenas um 🤝 . Vlw, espero ter ajudado!! abraços! 🚀

2023-05-29 00:14 UTC, aprendendofelipe approved these changes

2023-05-29 00:18 UTC, merged

2023-05-29 00:22 UTC, aprendendofelipe commented
Em produção! 🚀🚀🚀

@JoandersonPaiva, bem vindo à Turma de contribuidores do TabNews! 👏👏👏

2023-05-29 01:26 UTC, JoandersonPaiva commented
> Em produção! 🚀🚀🚀
> 
> @JoandersonPaiva, bem vindo à Turma de contribuidores do TabNews! 👏👏👏

@aprendendofelipe que top! Muito obrigado! espero poder contribuir mais no futuro! 👊

2023-05-29 12:25 UTC, filipedeschamps commented
Belo trabalho turma!! 😍 😍 😍

Fiquei com uma dúvida quanto ao:

https://github.com/filipedeschamps/tabnews.com.br/blob/c71479e0d024f4313028dc0e114671b955891100/models/authorization.js#L48

Qual a razão de retornar sempre `true` caso não tenha `resource`?

2023-05-29 13:52 UTC, aprendendofelipe commented
> Qual a razão de retornar sempre `true` caso não tenha `resource`?

Se não tem `resource` a verificação é apenas da `feature`, o que já passou no passo anterior

2023-05-29 13:54 UTC, aprendendofelipe commented
Só lembrando que isso não mudou, apenas não era visível antes

2023-05-29 14:15 UTC, JoandersonPaiva commented
> Se não tem `resource` a verificação é apenas da `feature`, o que já passou no passo anterior
exatamente! mais sucinto impossível haha

2023-06-01 02:16 UTC, JoandersonPaiva commented
> @JoandersonPaiva você foi citado no post comemorativo:https://www.tabnews.com.br/FelipeBarso/tabnews-novo-ranqueamento-otimizacoes-e-mais 🎉

Caramba que dahora!! tmj @aprendendofelipe 👊