feat: create interaction hook with native TTS
filipedeschamps/tabnews.com.br pull request #1434
Opened 2023-06-03 00:55 UTC by silvaezequias

2023-06-06 01:42 UTC, vilarjp commented
> Ainda não tem suporte para mobile, não sei qual seria a melhor forma de fazer isso. O layout quebra quando o menu de fala é ativado:
> 
> ![TTS em um display mobile](https://user-images.githubusercontent.com/63757378/243438342-318f55c2-ccbb-4957-97d0-90678644fb6f.png)
> 
> Enquanto na versão desktop está tudo certo
> 
> ![TTS em um display desktop](https://user-images.githubusercontent.com/63757378/243438732-38eb42b5-7289-46ac-af09-78346827d3c4.png)
> 
> O pessoal do front se puder dar uma força nisso ai, não é o meu forte! 🤝

@silvaezequias não consegui identificar onde que o layout quebra na opção mobile, no seu print me pareceu tudo certo, também rodei a sua branch aqui no meu ambiente local e me pareceu tudo ok, consegue passar mais informações?

2023-06-06 03:58 UTC, silvaezequias commented
> @silvaezequias não consegui identificar onde que o layout quebra na opção mobile, no seu print me pareceu tudo certo, também rodei a sua branch aqui no meu ambiente local e me pareceu tudo ok, consegue passar mais informações?

Cara, eu peço perdão pois mandei o print errado. O volume e a velocidade de fala possuem um slider para gerenciar eles. Esse slider aparece quando o usuário passar o mouse por cima, igual nesse exemplo: 

![Screenshot_1](https://github.com/filipedeschamps/tabnews.com.br/assets/63757378/fc9f37cf-caf8-4e89-81c7-4feb83df03cb)

Da forma que está, não funciona no mobile porque não tem como fazer um hover dinamico e quando o usuário clica no botão, ele abre o slider e quebra o layout dos botões e fica fora da tela.

![Screenshot_2](https://github.com/filipedeschamps/tabnews.com.br/assets/63757378/4f4cad80-9407-4c0f-89f3-00942dc5b76d)

Teria que ter uma outra forma de gerenciar a velocidade e o volume pelo mobile, não sei qual seria a melhor forma de fazer isso. Uma das formas que eu pensei foi um dropdown menu com as opções de gerenciamento.

2023-06-06 04:06 UTC, silvaezequias commented on pages/interface/hooks/useTextToSpeech/index.js
> +  function setVolume(value) {
Esse gerenciamento de volume está um pouco errado, está aumentando muito pouco o volume e abaixando pouco e no momento que chega em 0 ele simplesmente corta o volume.

2023-06-06 15:19 UTC, silvaezequias commented
Fechou @aprendendofelipe e obrigado por fornecer o link do ambiente de testes! 🤝

Em relação a issue sobre esse pull request, eu vou abrir sim, mas logo depois de resolver alguns problemas de usabilidade.

--- 
### +Bug

**Eu encontrei mais um bug**: Quando o áudio está tocando, se mudar de janela pelo sistema do react (sem recarregar a pagina) o áudio continua tocando.

2023-06-07 14:47 UTC, silvaezequias commented on pages/interface/hooks/useTextToSpeech/index.js
> +  function setVolume(value) {
Consertado: https://github.com/filipedeschamps/tabnews.com.br/pull/1434/commits/60655a8d55835d52cee8780201af666f71172422

2023-06-08 19:24 UTC, silvaezequias commented
> ### +Bug
> **Eu encontrei mais um bug**: Quando o áudio está tocando, se mudar de janela - provavelmente usando o componente Link do NextJs - pelo sistema do react (sem recarregar a pagina), o áudio continua tocando.

Resolvido: https://github.com/filipedeschamps/tabnews.com.br/pull/1434/commits/493b3cbf8a00df8774077d33ebf673d6cc8d12bd

2023-06-10 20:58 UTC, silvaezequias commented
Menu de gerenciamento de TTS adicionado para mobile: https://github.com/filipedeschamps/tabnews.com.br/pull/1434/commits/486302cb4ec4672088b5f84a1fa4c090d411a5f9

![mobile tabnews tts menu](https://github.com/filipedeschamps/tabnews.com.br/assets/63757378/9dd77174-cbdb-487b-9768-0ac2eb5065f6)

2023-06-28 12:30 UTC, aprendendofelipe requested changes
@silvaezequias, muito legal a funcionalidade, só que a UX não está legal:

1. É melhor não haver nenhum layout shift como o que ocorre com o hover no modo desktop.
2. Não está intuitiva a maneira de mudar a velocidade de leitura. Fiquei clicando no 1.0x, pois inclusive o cursor induz que ali é clicável. Imaginava que abriria algo na vertical para selecionar os números e que aquele controle azul era da evolução da leitura e não da velocidade. Provavelmente teria a mesma dificuldade com o controle de volume se já não tivesse passado pelo problema com a velocidade. Acho que pode ficar mais claro se esses controles surgirem na vertical, abaixo de cada botão. E faria o mesmo na versão mobile.
3. Senti falta de um controle para avançar e recuar na leitura. Esse sim acho que faz mais sentido ser na horizontal.

Fora a UX, o botão "continuar narração" não está funcionando no mobile.

Ainda não revisei o código 👍

2023-08-21 09:50 UTC, closed without merging