Feat reading time on posts
filipedeschamps/tabnews.com.br pull request #1445
Opened 2023-06-13 21:47 UTC by ValbertMartins

Esse pr adiciona a feature de tempo de leitura estimado a cada post ao entrar no post.

Como base, segui o que o [medium.com](url) utiliza, 260/270 wpm(words per minute) e arrendondar para cima os segundos restantes.

Artigo base do medium: 
https://blog.medium.com/read-time-and-you-bc2048ab620c

![Captura de tela 2023-06-13 181737](https://github.com/filipedeschamps/tabnews.com.br/assets/112519905/c64c5d27-608e-41d2-accf-56aed131a574)

2023-06-13 23:54 UTC, aprendendofelipe reviewed
Olá @ValbertMartins, obrigado pelo PR! 💪

Fiz uma sugestão e um comentário no código. O comentário é sobre a forma de contar as palavras. Queria saber a opinião da turma.

Outra coisa que queria saber a opinião é se a gente deveria mostrar o tempo de leitura em todos os comentários ou apenas na publicação principal. O que acham?

2023-06-13 23:54 UTC, aprendendofelipe commented on pages/interface/components/ReadTime/index.js
> +  return Math.ceil((wordsQuantity * 60) / wpm / 60);
```suggestion
  return Math.ceil(wordsQuantity / wpm);
```

2023-06-13 23:54 UTC, aprendendofelipe commented on pages/interface/components/ReadTime/index.js
> +  const wordsQuantity = text.split(' ').length;
Estou em dúvida se vale a pena fazer algo mais elaborado que remova o markdown e lide corretamente com quebras de linhas, sequências de espaços, etc.

Considerando que é apenas uma aproximação do tempo de leitura, provavelmente não vai valer a pena criar algo mais pesado, mas queria saber a opinião da turma

2023-06-14 00:23 UTC, ValbertMartins commented on pages/interface/components/ReadTime/index.js
> +  const wordsQuantity = text.split(' ').length;
Olá @aprendendofelipe  obrigado pelas sugestões,
 
Sobre ter tempo estimado nos comentários, também fico na dúvida, por um lado há comentários muito bem elaborados que dariam outro post, já para comentários curtos e diretos parece ficar redundante.

já a respeito de fazer algo mais elaborado para calcular essa média como no fim é apenas uma estimativa, também não sei vale a pena, já que isso pode variar em diversos fatores como complexidade do post, imagens e etc, então fica bem complexo ter uma estimativa bem precisa.

2023-06-14 10:23 UTC, thisiscleverson commented
Eu estou muito pessimista com essa feature. No meu ponto de vista isso desmotivaria o usuário a ler o post, além de que o tempo de leitura é muito relativo, existem muitas variáveis envolvida.

2023-06-17 19:40 UTC, H4ad requested changes

2023-06-17 19:40 UTC, H4ad commented on pages/interface/components/ReadTime/index.js
> +  );
Não sei quantas vezes isso pode renderizar, mas seria melhor salvar o `getReadTime(text)` em um `useMemo` ou apenas em uma simples variável.

2023-06-17 19:42 UTC, H4ad commented on pages/interface/components/ReadTime/index.js
> +  const wordsQuantity = text.split(' ').length;
Provavelmente performance não seria um problema aqui mas se tu quiser deixar mais rápido:

- Usa a lib [alfaaz](https://github.com/thecodrr/alfaaz), 2x mais rápido que split
- Ou troca o `.split` por um simples for, isso consumiria menos memória já que não precisa alocar para dividir o texto inteiro.

2023-06-21 00:54 UTC, Mazin97 commented
Concordo parcialmente com o @thisiscleverson. Isso pode ser algo que desencoraje o pessoal a ler. Mas também, pode ser uma mão na roda.. que tal isso ser configurável? Como se fosse um tipo de preferência de perfil ou algo do tipo. Sei que aumenta bem a complexidade da PR, mas é uma maneira de disponibilizar para quem quiser.

Sobre o tempo de leitura em respostas/comentários.. minha opinião pessoal é de que seja válido sim! pois pelo que navego no TabNews, vejo respostas longas com frequência hehehe

2023-06-22 20:38 UTC, RobertDS07 approved these changes
Bela iniciativa meu parceiro, parabéns.

2023-06-22 20:38 UTC, RobertDS07 commented on pages/interface/components/ReadTime/index.js
> +function getReadTime(text, wpm = 260) {
Fiquei curioso para saber o porquê da declaração da função fora do escopo do componente.

Seria para evitar a re-criação?

2023-06-22 20:38 UTC, RobertDS07 commented on pages/interface/components/ReadTime/index.js
> +function getReadTime(text, wpm = 260) {
Será que vale deixar o wpm mutável? 

Talvez sim, mas tentei pensar aqui no caso de uso que alteraríamos e não encontrei, talvez tornar ele uma const, não sei, o que acha?

```suggestion
const WORDS_PER_MINUTE = 260

function getReadTime(text) {
```

2023-06-22 20:38 UTC, RobertDS07 commented on pages/interface/components/ReadTime/index.js
> +function getReadTime(text, wpm = 260) {
Fiquei um pouco na dúvida de em qual unidade de medida iria retornar, talvez explicitar isto facilite a leitura, o que acha?

```suggestion
function getReadTimeInMinutes(text, wpm = 260) {
```

2023-06-24 18:26 UTC, ValbertMartins commented on pages/interface/components/ReadTime/index.js
> +  );
@H4ad feito

2023-06-24 18:28 UTC, ValbertMartins commented on pages/interface/components/ReadTime/index.js
> +function getReadTime(text, wpm = 260) {
@RobertDS07 boa, feito!

2023-06-24 22:53 UTC, aprendendofelipe commented on pages/interface/components/ReadTime/index.js
> +    const wordsQuantity = text.split(' ').length;
```suggestion
    const wordsQuantity = text.split(/[^A-Za-z]+/).length;
```

Uma alternativa um pouco mais precisa quando houver sequências de espaços, quebras de linhas e outros caracteres diferentes de letras.

2023-06-24 23:31 UTC, aprendendofelipe commented on pages/interface/components/Content/index.js
> +            <ReadTime text={contentObject.body} />
Que tal usar `{' · '}` como separador, assim como no `contentList`?

2023-06-24 23:31 UTC, aprendendofelipe commented on pages/interface/components/ReadTime/index.js
> +      {`${readTimeInMinutes} ${readTimeInMinutes === 1 ? 'minuto' : 'minutos'} de leitura`}
Já que está usando o `useMemo`, pode retornar a string completa já formatada.

E também pode usar a abreviação "min" ao invés de alternar entre "minuto" e "minutos".

Veja duas diferentes sugestões (a terceira é a versão atual):

![image](https://github.com/filipedeschamps/tabnews.com.br/assets/77860630/032e212c-7ee7-4db0-a111-aad7273c7481)

2023-06-25 17:47 UTC, ValbertMartins commented on pages/interface/components/ReadTime/index.js
> +    const wordsQuantity = text.split(' ').length;
feito!

2023-06-25 17:48 UTC, ValbertMartins commented on pages/interface/components/ReadTime/index.js
> +      {`${readTimeInMinutes} ${readTimeInMinutes === 1 ? 'minuto' : 'minutos'} de leitura`}
@aprendendofelipe implementei a sugestão 2!

2023-06-25 18:02 UTC, ValbertMartins commented on pages/interface/components/Content/index.js
> +            <ReadTime text={contentObject.body} />
![image](https://github.com/filipedeschamps/tabnews.com.br/assets/112519905/61b919cd-ef43-486c-a029-0f8abda9592f)

@aprendendofelipe aos espaçadores estou com um problema quanto a margem esquerda que já existia no componente PublishedSince, já que se remover esse ml do PublishedSince, dentro do contentList ele não ficará alinhado. tem alguma sugestão?

2023-06-25 19:15 UTC, aprendendofelipe commented on pages/interface/components/Content/index.js
> +            <ReadTime text={contentObject.body} />
Está ficando show de bola, @ValbertMartins! 💪

Se não quiser ter que arrumar o `PublishedSince` e o `contentList`, então basta passar `sx={{ ml: 0}}` para o `PublishedSince` dentro do `Content`:

```js
<PublishedSince direction="n" date={contentObject.published_at} sx={{ ml: 0 }} />
```

Agora o ideal mesmo seria inverter. Retirar o `ml` de dentro do componente `PublishedSince` e passar `sx={{ ml: 1}}` ao usar o componente em `contentList`. Mas fica a seu critério. 👍

Eu só não colocaria o separador entre no `username` e `ReadTime` , mas apenas entre `ReadTime` e `PublishedSince`.

E pensando mais sobre mostrar o tempo de leitura nos comentários. Acho melhor não mostrar por enquanto, pois vai piorar a quebra de layout que já ocorre em repostas em níveis mais profundos, por exemplo aqui:

https://tabnews-git-fork-valbertmartins-feat-reading-tim-1db7eb-tabnews.vercel.app/Gustavo33/teste4593832181797422292334945798549354624941348715825899669

Dependendo da aceitação da nova funcionalidade, podemos ver como fazer com os comentários e, mais importante, ver como podemos mostrar o tempo de leitura no `contentList` 🤝

2023-06-26 21:35 UTC, ValbertMartins commented on pages/interface/components/ContentList/index.js
> +              <PublishedSince direction="nw" date={contentObject.published_at} sx={{ position: 'absolute', ml: 1 }} />
tive que também trazer o position para fora do componente, já que só aplicar o ml apenas estava sobrescrevendo ficando sem o position, logo causando esse problema  no tooltip

![image](https://github.com/filipedeschamps/tabnews.com.br/assets/112519905/997fd69b-d2c8-4ec3-a4b5-15e6c970f76b)

2023-06-26 21:37 UTC, ValbertMartins commented on pages/interface/components/PublishedSince/index.js
> +    <Tooltip sx={{ position: 'absolute' }} aria-label={tooltipLabel} suppressHydrationWarning {...props}>
resolvi deixar o position também dentro do componente, já que sem ele vi que o tooltip fica com alguns problemas.

2023-06-26 21:51 UTC, ValbertMartins commented on pages/interface/components/Content/index.js
> +            <ReadTime text={contentObject.body} />
obrigado @aprendendofelipe !

Fiz a remoção do tempo de leitura dos comentários e a remoção do separador entre o username e o readTime.  

![image](https://github.com/filipedeschamps/tabnews.com.br/assets/112519905/71455189-b2f0-4d12-9c9f-3415aeb4660f)


No caso do `PublishedSince` além de remover o `ml:1` de dentro do componente como sua sugestão, também tive que trazer o `position:absolute `dele quando usado no contentList.

2023-06-26 22:14 UTC, aprendendofelipe commented on pages/interface/components/PublishedSince/index.js
> +    <Tooltip sx={{ position: 'absolute' }} aria-label={tooltipLabel} suppressHydrationWarning {...props}>
Sim @ValbertMartins, esse `position` é necessário, pois o Tooltip do Primer ainda contém bugs por estar em alpha.

2023-06-26 22:15 UTC, aprendendofelipe commented
Parece que está pronto! 🎉

Vamos só aguardar a Turma dar uma avaliada no resultado em homologação: 🤝

https://tabnews-ho4w6beg5-tabnews.vercel.app/Ezequias/publicacao-ficticia-para-teste-de-tts

2023-06-28 11:37 UTC, aprendendofelipe approved these changes

2023-06-28 11:41 UTC, merged

2023-06-28 11:47 UTC, aprendendofelipe commented
Em produção! 🚀🚀🚀

@ValbertMartins, bem vindo à Turma de contribuidores do TabNews! 👏👏👏