refactor(icon imports): change icon imports to TabNewsUI/icons
filipedeschamps/tabnews.com.br pull request #1489
Opened 2023-07-27 16:03 UTC by ValbertMartins

• Esse pr refatora a importação dos icones para um só lugar, `/TabNewsUI/icons`.

• a subpasta icons é para não misturar a importação de `componentes` e `icones` tudo dentro de `TabNewsUI`

2023-07-27 18:24 UTC, aprendendofelipe requested changes
@ValbertMartins, obrigado pelo PR! 💪

Faltou exportar o `CommentIcon`.

Também fiz algumas sugestões no código 👍

2023-07-27 18:24 UTC, aprendendofelipe commented on pages/interface/components/TabNewsUI/icons/index.js
> +  CommentDiscussionIcon,
```suggestion
  CommentDiscussionIcon,
  CommentIcon,
```

2023-07-27 18:24 UTC, aprendendofelipe commented on pages/[username]/index.public.js
> +import { FaUser } from '@/TabNewsUI/icons';
```suggestion
```

2023-07-27 18:24 UTC, aprendendofelipe commented on pages/[username]/index.public.js
> +import { KebabHorizontalIcon, TrashIcon } from '@/TabNewsUI/icons';
```suggestion
import { FaUser, KebabHorizontalIcon, TrashIcon } from '@/TabNewsUI/icons';
```

2023-07-27 18:24 UTC, aprendendofelipe commented on pages/interface/components/Header/index.js
> +import { HomeIcon, PersonFillIcon, SquareFillIcon, PlusIcon } from '@/TabNewsUI/icons';
```suggestion
import { CgTab, HomeIcon, PersonFillIcon, SquareFillIcon, PlusIcon } from '@/TabNewsUI/icons';
```

2023-07-27 18:24 UTC, aprendendofelipe commented on pages/interface/components/Header/index.js
> +import { CgTab } from '@/TabNewsUI/icons';
```suggestion
```

2023-07-27 19:19 UTC, brunofamiliar commented
Sei que no momento não é uma "dor". Mas já tive problemas quando um projeto começa a escalar em quantidade de features onde é necessário uma quantidade maior de ícones. Utilizar lib's assim pode onerar no sentido de que, para cada novo ícone teremos que entrar em "@/TabNewsUI/icons", adicionar esse novo ícone, para só então conseguir utilizar em outra parte do sistema. Não seria viável utilizar soluções como por exemplo o [iconify](https://icon-sets.iconify.design/)? Ele consegue centralizar várias soluções das principais lib's de icones existentes (assim como o react-icons faz). O diferencial é que é importado apenas um único componente (<Icon />), passando como parâmetro o `icon` desejado.

2023-07-27 20:52 UTC, ValbertMartins commented on pages/interface/components/Header/index.js
> +import { HomeIcon, PersonFillIcon, SquareFillIcon, PlusIcon } from '@/TabNewsUI/icons';
obrigado @aprendendofelipe 💪. 

Deslize meu, não notei que tinham componentes que faziam a exportação de ambos

2023-07-27 22:03 UTC, aprendendofelipe approved these changes

2023-07-30 21:22 UTC, aprendendofelipe commented
> Utilizar lib's assim pode onerar no sentido de que, para cada novo ícone teremos que entrar em "@/TabNewsUI/icons", adicionar esse novo ícone, para só então conseguir utilizar em outra parte do sistema.

Não sei se entendi qual é o ponto que você quiz dizer com "lib's assim", mas esse PR eu não enxergo como algo que onera, mas sim como algo que organiza e facilidade manutenção, já que fica muito mais fácil substituir qualquer biblioteca de ícones caso seja necessário. Também facilita para quem quiser adicionar ícones em qualquer ponto do sistema, pois fica fácil saber o que já existe ou não no projeto.

> Não seria viável utilizar soluções como por exemplo o [iconify](https://icon-sets.iconify.design/)? Ele consegue centralizar várias soluções das principais lib's de icones existentes (assim como o react-icons faz). O diferencial é que é importado apenas um único componente (`<Icon />`), passando como parâmetro o `icon` desejado.

Não sei se existiria alguma vantagem em usar essa lib especificamente, mas, se for o caso, eu tentaria usá-la de maneira que fosse fácil de substituí-la a qualquer momento, ou seja, importaria a biblioteca em um único arquivo e usaria no restante do sistema através desse ponto centralizado, assim como está sendo feito nesse PR.

2023-07-30 21:24 UTC, merged

2023-07-30 21:28 UTC, aprendendofelipe commented
Em produção 🚀🚀🚀

2023-11-21 19:15 UTC, aprendendofelipe commented
@ValbertMartins, você foi citado no post comemorativo:

https://www.tabnews.com.br/FelipeBarso/parabens-tabnews-aniversario-de-lancamento-e-mais-melhorias 🎉