feat: adiciona indicação dos termos de uso na tela de cadastro
filipedeschamps/tabnews.com.br pull request #1494
Opened 2023-08-06 22:10 UTC by luizfelipemacedoc

Primeira passo da implementação da _issue_: https://github.com/filipedeschamps/tabnews.com.br/issues/1153

2023-08-07 12:35 UTC, aprendendofelipe reviewed
Show @luizfelipemacedoc, obrigado pelo PR! 💪

Para aprovar, eu preciso que você edite a mensagem do commit para que ela fique em inglês. Consegue fazer isso? 🤝

Opcionalmente, caso queira incrementar o PR...

Que tal adicionar um `Checkbox` que precise ser selecionado antes de submeter o cadastro?

Dá para fazer isso desabilitando o botão `Criar Cadastro` e só habilitando se o `Checkbox` for selecionado, mas acho que seria melhor deixar o botão habilitado, mas mostrar um aviso caso ele seja clicado sem marcar que concorda com os termos.

Veja essa parte do código se precisar de inspiração:

https://github.com/filipedeschamps/tabnews.com.br/blob/49aadd347f6619173235c924ba44f64316e86db4/pages/perfil/index.public.js#L261

O que acha?

2023-08-08 00:38 UTC, luizfelipemacedoc commented
> Show @luizfelipemacedoc, obrigado pelo PR! 💪
> 
> Para aprovar, eu preciso que você edite a mensagem do commit para que ela fique em inglês. Consegue fazer isso? 🤝
> 
> Opcionalmente, caso queira incrementar o PR...
> 
> Que tal adicionar um `Checkbox` que precise ser selecionado antes de submeter o cadastro?
> 
> Dá para fazer isso desabilitando o botão `Criar Cadastro` e só habilitando se o `Checkbox` for selecionado, mas acho que seria melhor deixar o botão habilitado, mas mostrar um aviso caso ele seja clicado sem marcar que concorda com os termos.
> 
> Veja essa parte do código se precisar de inspiração:
> 
> https://github.com/filipedeschamps/tabnews.com.br/blob/49aadd347f6619173235c924ba44f64316e86db4/pages/perfil/index.public.js#L261
> 
> O que acha?

2023-08-08 00:46 UTC, luizfelipemacedoc commented
> Show @luizfelipemacedoc, obrigado pelo PR! 💪
> 
> Para aprovar, eu preciso que você edite a mensagem do commit para que ela fique em inglês. Consegue fazer isso? 🤝
> 
> Opcionalmente, caso queira incrementar o PR...
> 
> Que tal adicionar um `Checkbox` que precise ser selecionado antes de submeter o cadastro?
> 
> Dá para fazer isso desabilitando o botão `Criar Cadastro` e só habilitando se o `Checkbox` for selecionado, mas acho que seria melhor deixar o botão habilitado, mas mostrar um aviso caso ele seja clicado sem marcar que concorda com os termos.
> 
> Veja essa parte do código se precisar de inspiração:
> 
> https://github.com/filipedeschamps/tabnews.com.br/blob/49aadd347f6619173235c924ba44f64316e86db4/pages/perfil/index.public.js#L261
> 
> O que acha?

Obrigado pelo retorno, @aprendendofelipe 🤝
Subi um novo `commit` em inglês com o adicional de um `checkbox` ao lado da indicação dos termos de uso.  No qual, optei por utilizar a estratégia de desabilitar o botão caso não seja marcado o `check`.

2023-08-08 13:38 UTC, aprendendofelipe requested changes
Legal @luizfelipemacedoc! 💪

Sobre os commits, o ideal é unificá-los (faz um squash), mas se tiver dificuldades, pode deixar que eu faço antes de mesclar. 🤝

Por favor, veja também meus comentários no código. 👍

Um dos comentários trata da organização dos imports. @MattFerreira18, ou quem puder, que tal abrir um PR atualizado do que foi feito em #552? 💪

2023-08-08 13:38 UTC, aprendendofelipe commented on pages/cadastro/index.public.js
> +          <input type="checkbox" checked={isCheckboxChecked} onClick={() => setIsCheckboxChecked(!isCheckboxChecked)} />
Melhor usar o [`Checkbox` da biblioteca Primer](https://primer.style/react/Checkbox), pois mesmo ele ainda estando em versão alpha, conforme a biblioteca for evoluindo, vamos ganhando as melhorias, por exemplo, de estilização e acessibilidade.

Se tiver problemas com alinhamento, talvez o que foi feito no PR #1173 possa ajudar.

2023-08-08 13:38 UTC, aprendendofelipe commented on pages/cadastro/index.public.js
> +            Ao criar um cadastro, você sinaliza estar de acordo com os{' '}
Essa mensagem precisa ser adequada, pois não é mais a criação do cadastro que sinaliza estar de acordo, mas sim o checkbox.

Deve funcionar melhor o clássico "Li e estou de acordo com os Termos de Uso".

2023-08-08 13:38 UTC, aprendendofelipe commented on pages/cadastro/index.public.js
> +  Text,
```suggestion
  Link,
  PasswordInput,
  Text,
  TextInput,
```

Já que vai precisar mudar outras coisas no código, vamos tentar deixar as importações organizadas para exigir menos mudanças quando adotarmos algum plugin que faça isso automaticamente.

2023-08-08 13:43 UTC, MattFerreira18 commented
> Um dos comentários trata da organização dos imports. @MattFerreira18, ou quem puder, que tal abrir um PR atualizado do que foi feito em #552? 💪

Opaa só bora @aprendendofelipe, tinha até esquecido desse meu PR rs. Vou fazer os ajustes necessários e já implementar oq foi feito em #552 pro código atualizado.

2023-08-10 13:21 UTC, aprendendofelipe approved these changes

2023-08-10 13:24 UTC, merged

2023-08-10 13:31 UTC, aprendendofelipe commented
Boa @luizfelipemacedoc, sua contribuição já foi para produção! 🚀🚀🚀

Bem vindo à Turma de contribuidores do TabNews! 👏👏👏

2023-11-21 19:15 UTC, aprendendofelipe commented
@luizfelipemacedo, você foi citado no post comemorativo:

https://www.tabnews.com.br/FelipeBarso/parabens-tabnews-aniversario-de-lancamento-e-mais-melhorias 🎉