refactor(site description): change the description to be consistent w…
filipedeschamps/tabnews.com.br pull request #1498
Opened 2023-08-15 04:06 UTC by VictorManhani

PR sobre a issue #1497

2023-09-14 17:40 UTC, mayconbalves approved these changes

2023-10-04 19:10 UTC, gbrocha approved these changes

2023-10-06 17:55 UTC, edinelsonslima approved these changes

2023-10-12 12:20 UTC, Poveii commented
Essa PR tá pronta pro merge? É algo tão simples, de fácil implementação em produção.

2023-10-22 05:55 UTC, burn-c approved these changes

2023-12-07 22:16 UTC, Rafatcb requested changes
Me parece que faltou mudar aqui:

https://github.com/filipedeschamps/tabnews.com.br/blob/086931bf643047a033280332897a9fe72473a995/pages/interface/components/Head/index.js#L17-L19

Quando for mergear, vale a pena mudar o `About` do repositório também.

Além disso, é importante ler o comentário do Felipe Barso https://github.com/filipedeschamps/tabnews.com.br/issues/1497#issuecomment-1846507752 para pensarmos numa descrição melhor.

2023-12-31 12:10 UTC, Rafatcb commented
Pessoal, estou fechando este PR para organizar o repositório porque já está aberto há algum tempo e não teve um andamento conforme o comentário do Felipe em https://github.com/filipedeschamps/tabnews.com.br/issues/1497#issuecomment-1846507752.

O issue #1497 ainda está aberto para implementação, mas é preciso chegar num consenso antes sobre qual seria um bom texto. Quando surgir uma boa descrição, um novo PR pode ser aberto, criando uma nova branch a partir do `main` para evitar conflitos, e também modificando o arquivo que deixei no meu comentário ao revisar o código.

Obrigado pelo PR e pelo issue, @VictorManhani!

2023-12-31 12:10 UTC, closed without merging