Adiciona ícone de carregamento no botão de publicar
filipedeschamps/tabnews.com.br pull request #1501
Opened 2023-08-25 02:25 UTC by mihtoa

Implementação do ícone de carregamento no botão de publicar, conforme foi sugerido na issue #788.

| Antes | Depois |
|-------|--------|
|   <img width="100" alt="antes" src="https://github.com/filipedeschamps/tabnews.com.br/assets/32906579/ed73719e-e1be-42c4-bfc4-ee35723c8c6d">   |    <img width="125" alt="depois" src="https://github.com/filipedeschamps/tabnews.com.br/assets/32906579/6bd19030-852c-49a8-8bb9-b3d3194fb261">    |

2023-08-25 14:20 UTC, aprendendofelipe reviewed
Show @mihtoa, obrigado pelo PR! 💪

Por favor, veja se concorda com meus comentários no código. 👍

E que tal fazer o mesmo nos botões de outras telas como, por exemplo, no login, cadastro, recuperar senha, alterar senha, editar perfil etc.? Caso prefira, dá para criar um botão customizado para usar em todos esses locais, algo como:

```js
function ButtonWithStatus({ children, processing, sx, ...props }) {
  return (
    <Button
      leadingIcon={() => (processing ? <Spinner size="small" /> : <Box width="16px" />)}
      trailingIcon={() => <Box width="16px" />}
      sx={{ paddingX: 2, ...sx }}
      disabled={processing}
      {...props}>
      {children}
    </Button>
  );
}
```

A vantagem é que se depois a gente quiser mudar o tipo do feedback, a gente muda em um só lugar. Note que adicionei a propriedade `processing` , que eu não pensei muito no nome 😅, mas só para o componente ficar mais flexível e permitir passar o `disabled` separadamente se for necessário.

Mas são só sugestões, veja o que você acha que faz sentido e que tenha disponibilidade de fazer 🤝

2023-09-21 13:36 UTC, Guiflayrom approved these changes

2023-09-21 15:27 UTC, aprendendofelipe requested changes
Show @mihtoa, ficou muito legal 😍

Fiz sugestões no código, pois precisamos poder passar a propriedade `disabled` separadamente. Sem isso, o loading fica ativo indevidamente enquanto os termos não forem aceitos na tela de cadastro:

https://tabnews-git-fork-mihtoa-add-spinner-in-publish-button-tabnews.vercel.app/cadastro

![image](https://github.com/filipedeschamps/tabnews.com.br/assets/77860630/3adb0e39-5cb4-4313-9245-812235dd278f)

2023-09-21 15:27 UTC, aprendendofelipe commented on pages/cadastro/index.public.js
> +            isLoading={isLoading || !isTermsAccepted}>
```suggestion
            disabled={!isTermsAccepted}
            isLoading={isLoading}>
```

2023-09-27 23:07 UTC, mihtoa commented
> Show @mihtoa, ficou muito legal 😍
> 
> Fiz sugestões no código, pois precisamos poder passar a propriedade `disabled` separadamente. Sem isso, o loading fica ativo indevidamente enquanto os termos não forem aceitos na tela de cadastro:
> 
> https://tabnews-git-fork-mihtoa-add-spinner-in-publish-button-tabnews.vercel.app/cadastro
> 
> ![image](https://user-images.githubusercontent.com/77860630/269668847-3adb0e39-5cb4-4313-9245-812235dd278f.png)

Opa verdade, deixei passar, ajustado!

2023-09-28 11:46 UTC, aprendendofelipe approved these changes
Show! Vamos pro merge! 🎉🎉🎉

2023-09-28 11:55 UTC, merged

2023-09-28 12:08 UTC, aprendendofelipe commented
Boa @mihtoa, em produção! 🚀🚀🚀

Bem vinda à Turma de contribuidores do TabNews! 👏👏👏

2023-11-21 19:14 UTC, aprendendofelipe commented
@mihtoa, você foi citada no post comemorativo:

https://www.tabnews.com.br/FelipeBarso/parabens-tabnews-aniversario-de-lancamento-e-mais-melhorias 🎉