feat(save of edit profile): Gives a feedback to user when it save the changes
filipedeschamps/tabnews.com.br pull request #1543
Opened 2023-10-31 04:46 UTC by viniciusamc

Achei uma mudança interessante, vi no Issue uma recomendação para usar o Flash, utilizei ele. Ele aparece no lado superior direito da tela, em verde, e após 5 segundos ele desaparece 

#1524

2023-10-31 16:41 UTC, aprendendofelipe requested changes
Show @viniciusamc, fiz mais algumas sugestões no código. 👍

Aproveita também para fazer squash dos commits e deixar a mensagem mais impessoal 🤝

2023-10-31 16:41 UTC, aprendendofelipe commented on pages/perfil/index.public.js
> +          setGlobalSucessMessage(null);
Não acha melhor colocar tudo isso após o `else` ?

```suggestion
        if (user.email !== email) {
```


```js
    ...
    } else {
        clearTimeout(sucessTimeoutRef.current);

        setGlobalSucessMessage('Salvo com sucesso!');

        sucessTimeoutRef.current = setTimeout(() => {
          setGlobalSucessMessage(null);
        }, 5000);
    }

2023-10-31 16:41 UTC, aprendendofelipe commented on pages/perfil/index.public.js
> +  const [globalSucessMessage, setGlobalSucessMessage] = useState(null);
Apenas por organização, acho que essa linha ficaria melhor junto da que define `globalErrorMessage`.

Como já sugeri outra mudança, acho que compensa arrumar aqui também 👍

2023-11-02 02:52 UTC, wellwelwel commented
Opá, só uma dica simples: trocar onde aparece "sucess" por "success", por exemplo:
```diff
-  const [globalSucessMessage, setGlobalSucessMessage] = useState(null);
+  const [globalSuccessMessage, setGlobalSuccessMessage] = useState(null);
```

🙋🏻‍♂️

2023-11-02 03:12 UTC, aprendendofelipe commented
Boa @wellwelwel, acredito que o @viniciusamc só aceitou a sugestão com o meu erro de digitação 😅

@viniciusamc, só vi que o PR já estava pronto para ser revisado por causa da mensagem do @wellwelwel. Pelo jeito é só esse erro de digitação que falta mesmo. 🎉

Quando corrigir a palavra "success", faz um novo squash dos commits, mas deixa a mensagem em inglês, que é o padrão dos commits do projeto 👍

Daí me avisa quando estiver pronto para o merge 🤝

2023-11-02 04:12 UTC, viniciusamc commented
> Boa @wellwelwel, acredito que o @viniciusamc só aceitou a sugestão com o meu erro de digitação 😅
> 
> @viniciusamc, só vi que o PR já estava pronto para ser revisado por causa da mensagem do @wellwelwel. Pelo jeito é só esse erro de digitação que falta mesmo. 🎉
> 
> Quando corrigir a palavra "success", faz um novo squash dos commits, mas deixa a mensagem em inglês, que é o padrão dos commits do projeto 👍
> 
> Daí me avisa quando estiver pronto para o merge 🤝

Ok, provavelmente o merge está pronto

2023-11-02 19:02 UTC, viniciusamc commented
Acho que todas as correções já foram feitas e o merge possivelmente está pronto @aprendendofelipe

2023-11-02 19:50 UTC, aprendendofelipe commented
@viniciusamc, quando você fez o squash, acabou removendo commits de antes do seu PR. Além disso, você me deixou como autor do commit.

Como removeu os commits, precisei fazer rebase, mas daí seu usuário nem aparece mais vinculado ao commit, pois você já tinha me deixado como autor.

Se fizer merge assim, você não vai entrar na lista de contribuidores.

Recomendo você fazer pull da versão atual no GitHub, então fazer um `git reset --soft ad30e20a3bffc84aadc15c3b3bcecd753627acb3` e criar novamente seu commit com você como autor 👍

2023-11-02 19:53 UTC, closed without merging