feat(GoToTopButton): add tooltip direction to button component
filipedeschamps/tabnews.com.br pull request #1807
Opened 2024-10-26 15:02 UTC by emerson-oliveira

## Mudanças realizadas

Alteração da posição do `Tooltip` para sempre ficar visível.

**Antes:**
![image](https://github.com/user-attachments/assets/7ae13496-b48c-4ca3-854e-9821f3399bbd)

**Depois:**
![image](https://github.com/user-attachments/assets/cbda7d8d-c973-4616-9765-c11fb98b4c92)

Resolve  #1802 
## Tipo de mudança

- [x] Correção de bug

## Checklist:

- [x] As modificações não geram novos logs de erro ou aviso (_warning_).
- [x] Eu adicionei testes que provam que a correção ou novo recurso funciona conforme esperado.
- [x] Tanto os novos testes quanto os antigos estão passando localmente.

2024-10-26 18:49 UTC, Rafatcb approved these changes
Show! Obrigado por investigar o problema :+1:

2024-10-26 19:32 UTC, aprendendofelipe commented
@emerson-oliveira, muito obrigado pelo PR! 💪

Melhorou porque, por algum motivo, ignorou o `n` e está assumindo `nw`. Parece que agora tem uma automação no posicionamento do `Tooltip`, mas não está perfeita, senão não iria ocorrer o bug descrito em #1802.

Não estou acompanhando as atualizações do `Tooltip v2` para ter certeza sobre como está funcionando em caso de falta de espaço, mas como o `Tooltip v2` ainda é beta, e o `IconButton` está em alpha, tudo pode mudar. Inclusive a gente nem tinha esse `Tooltip`, e ele só surgiu por uma mudança do `IconButton` na biblioteca.

Por tudo isso, acho melhor deixar o posicionamento correto que precisamos, ou seja, `nw`. Precisamos que o posicionamento do `Tooltip` seja sempre  `nw`, já que o botão `Retornar ao Topo` sempre é posicionado no canto inferior direito.

2024-11-04 12:12 UTC, aprendendofelipe requested changes

2024-11-04 12:12 UTC, aprendendofelipe commented on pages/interface/components/GoToTopButton/index.js
> +        tooltipDirection="n"
```suggestion
        tooltipDirection="nw"
```

2024-11-04 12:28 UTC, merged

2024-11-04 12:32 UTC, aprendendofelipe commented
Em produção com a direção `nw` 🤝