feat(check the installed docker version): script to check version
filipedeschamps/tabnews.com.br pull request #1810
Opened 2024-11-02 05:11 UTC by rodrigoKulb

Script to check the installed docker and compose dependency

## Mudanças realizadas

Aqui vai uma sugestão para verificar a dependência do docker, a ideia partiu do inssue #1808 

## Tipo de mudança

[x] Nova funcionalidade

## Checklist:

- [x] As modificações não geram novos logs de erro ou aviso (_warning_).
- [ ] Eu adicionei testes que provam que a correção ou novo recurso funciona conforme esperado.
- [x] Tanto os novos testes quanto os antigos estão passando localmente.

2024-11-04 12:41 UTC, aprendendofelipe commented
Fala Rodrigão, obrigado pelo PR! 💪

Acho que o custo para manter esse código atualizado e útil não vai compensar algum benefício que ele traga.

E normalmente as mensagens de erro originais recebidas ao tentar rodar o projeto sem as dependências já são suficientes para entender qual é o problema.

O que acham?

2024-11-04 12:58 UTC, rodrigoKulb commented
Bom dia @aprendendofelipe, gosto da ideia de o "instalador" configurar automaticamente todas as dependências, mas sabemos que o Docker funciona de forma muito diferente em cada sistema operacional. Atualmente, apenas o Docker não está na lista de versões e instalação no `package.json`. Pesquisei alguma maneira de unificar isso no `package.json`, mas ele não faz parte dos pacotes do Node, então acabou ficando de fora.

Quanto à instalação do código, você se refere o número das duas versões? O restante é apenas `if`, `exec` e `console`.

De qualquer forma, foi só uma sugestão. Se você achar que o custo-benefício não compensa, seguimos sem! 👊️ 

Valeu pelo exercício! Aliás, você chegou a testar no Windows? Funcionou bem? Só testei no Linux. Só curiosidade mesmo!

2025-02-14 07:09 UTC, wellwelwel requested changes
Desculpe pela intromissão, acabei tomando a liberdade de revisar e também aproveitar para sugerir uma ideia mais fácil de manter 🙋🏻‍♂️

Ao invés de um _script_ que verifique pelo **Docker** e suas devidas versões e plugins, uma abordagem bastante simples seria incluir um sub tópico no [CONTRIBUTING.md](https://github.com/filipedeschamps/tabnews.com.br/blob/3161d2062de48f34e966297c0a7966e30fdf3ff3/CONTRIBUTING.md#L38):

> https://github.com/filipedeschamps/tabnews.com.br/blob/3161d2062de48f34e966297c0a7966e30fdf3ff3/CONTRIBUTING.md#L38 

Por exemplo, como eu faço isso nos meus projetos:

> <img width="609" alt="Screenshot 2025-02-14 at 03 58 16" src="https://github.com/user-attachments/assets/b1bf61fb-6fe6-460c-a8ee-3e0d80032278" />

2025-02-14 07:09 UTC, wellwelwel commented on dependency.js
> +    exec('killall node');
Esse comando só funciona no **Linux** e **macOS** e irá fechar 100% dos processos **Node.js**, não apenas o processo do **TabNews**.

2025-02-14 07:09 UTC, wellwelwel commented on dependency.js
> +exec('docker compose version', (err, stdout, stderr) => {
Para evitar ter que fechar os processos do **Node.js** manualmente, bastaria usar o `execSync`, já que ao retornar a primeira falha, ele não executaria as próximas etapas. Com isso o `killall` não seria mais necessário.

2025-05-29 22:48 UTC, Rafatcb commented
Como não ocorrerá o merge do PR, vou fechar para manter o repositório organizado. Agradeço pela contribuição e revisão dos envolvidos.

Se mudarem de ideia, basta reabrir o PR ou, se não for possível, abrir um novo.

2025-05-29 22:48 UTC, closed without merging