fix(recovery): recovery email message
filipedeschamps/tabnews.com.br pull request #819
Opened 2022-11-15 05:07 UTC by f-francine

Quando recebi o email de recuperação de senha, notei um errinho gramatical na mensagem quando é mencionado "uma solicitação foi solicitada". Esse PR visa corrigir esse erro, propondo uma pequena alteração na mensagem.

2022-12-21 21:09 UTC, aprendendofelipe requested changes
Boa @f-francine! Será que o correto não é a palavra "solicitada" no feminino? E a palavra "esta" não deveria ser substituída por "essa" ou "a"?

2022-12-23 16:10 UTC, f-francine commented on models/recovery.js
> +    text: `${user.username}, foi solicitado uma recuperação de senha. Caso você não tenha feito esta solicitação, ignore esse email.
boa!

2022-12-26 22:20 UTC, filipedeschamps approved these changes

2022-12-27 12:21 UTC, aprendendofelipe approved these changes

2022-12-27 12:24 UTC, merged

2022-12-27 12:28 UTC, aprendendofelipe commented
Em produção! 🚀