feat(publications): add share button in social networks (whatsapp, twitter, linkedin)
filipedeschamps/tabnews.com.br pull request #888
Opened 2022-11-22 10:15 UTC by fdc2001

Seguimento da sugestão: issues885

2022-11-22 10:42 UTC, brendo10x requested changes
Aprovado.

2022-11-22 10:42 UTC, brendo10x approved these changes

2022-11-22 11:44 UTC, mathantunes commented on pages/[username]/[slug]/index.public.js
> +  const shareText = `Olha%20este%20conteudo%20massa%20no%20tabnews!%20`;
Poderia utilizar a função encodeURI (https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/encodeURI) para gerar o encoding desejado.

E então o texto pode ser escrito sem o encode
'Olha este conteudo massa no tabnews! '

2022-11-22 11:48 UTC, fdc2001 commented on pages/[username]/[slug]/index.public.js
> +  const shareText = `Olha%20este%20conteudo%20massa%20no%20tabnews!%20`;
Não me lembrei dessa função, ando um pouco distante do javascript ultimamente, obrigado pela sugestão

2022-11-22 11:56 UTC, fdc2001 commented on pages/[username]/[slug]/index.public.js
> +  const shareText = `Olha%20este%20conteudo%20massa%20no%20tabnews!%20`;
Já adicionei a sua sugestão @mathantunes

2022-11-22 11:59 UTC, brendo10x commented on pages/[username]/[slug]/index.public.js
> +  const shareText = `Olha%20este%20conteudo%20massa%20no%20tabnews!%20`;
Show de bola.

2022-11-22 12:01 UTC, mathantunes submitted a review, later dismissed

2022-11-22 12:02 UTC, brendo10x submitted a review, later dismissed

2022-11-22 12:15 UTC, guilherssousa commented on pages/[username]/[slug]/index.public.js
> +  const shareText = encodeURI(`Olha este conteudo massa no tabnews! `);
Aviso bobinho, mas pode agregar: 
Quando usamos a função `encodeURI`, podemos usar caracteres especiais sem dor de cabeça, então fica tudo bem para usar pontuação ou outras coisas.

Que tal usar a frase `Olha este conteúdo massa no TabNews!`?

2022-11-22 12:16 UTC, guilherssousa submitted a review, later dismissed

2022-11-22 13:52 UTC, fdc2001 commented on pages/[username]/[slug]/index.public.js
> +                window.open('https://wa.me?text=' + shareText + window.location.href);
Gostei da sugestão e já atualizei obrigado

2022-11-22 13:52 UTC, fdc2001 commented on pages/[username]/[slug]/index.public.js
> +  const shareText = encodeURI(`Olha este conteudo massa no tabnews! `);
Realmente é bom usar os acentos, as vezes esqueço me deles de tanto codar 🤣

2022-11-22 14:04 UTC, guilherssousa approved these changes

2022-11-22 14:05 UTC, brendo10x approved these changes

2022-11-22 19:41 UTC, am-castro commented
Massa mano!

2022-11-22 19:47 UTC, mathantunes approved these changes

2022-12-09 12:46 UTC, aprendendofelipe commented
@fdc2001, obrigado pelo PR, mas assim como citei no PR #875, não houve uma prévia discussão sobre qual seria a real necessidade dos usuários do TabNews sobre essa funcionalidade. Por isso não tem como avaliar a implementação e vou fechar o PR por enquanto. Ok?

Recomendo discutir isso melhor em uma issue e, se for o caso, resgatarmos essa implementação.

Combiando? 🤝

2022-12-09 12:46 UTC, closed without merging