fix(confetti): adjust the window width of the confetti effect
filipedeschamps/tabnews.com.br pull request #889
Opened 2022-11-22 11:45 UTC by bralandealmeida

Ajusta largura da tela para o efeito de confetti na ativação do usuário. O bugfix corrige uma pequena questão de overflow que estava ocorrendo no navegador.

2022-11-24 18:52 UTC, aprendendofelipe commented
> Ajusta largura da tela para o efeito de confetti na ativação do usuário. O bugfix corrige uma pequena questão de overflow que estava ocorrendo no navegador.

Boa @bralandealmeida!

Nós temos esse componente em diversas páginas. Seria legal corrigir em todas ou, melhor ainda, criar um componente personalizado.

2022-11-25 21:11 UTC, bralandealmeida commented
> > Ajusta largura da tela para o efeito de confetti na ativação do usuário. O bugfix corrige uma pequena questão de overflow que estava ocorrendo no navegador.
> 
> Boa @bralandealmeida!
> 
> Nós temos esse componente em diversas páginas. Seria legal corrigir em todas ou, melhor ainda, criar um componente personalizado.

Feito!

2022-11-27 17:49 UTC, aprendendofelipe commented
@bralandealmeida, testei só nesse caminho e não está responsivo e também nunca termina o efeito:

https://tabnews-git-fork-bralandealmeida-bugfix-adjust-c-6354bf-tabnews.vercel.app/login/sucesso

2022-12-09 12:56 UTC, aprendendofelipe commented
@bralandealmeida fiz um novo deploy para mostrar o bug:

https://tabnews-git-fork-bralandealmeida-bugfix-adjust-c-6354bf-tabnews.vercel.app/login/sucesso

Estou alterando o PR para draft, ok? 🤝

2022-12-09 19:45 UTC, bralandealmeida commented
> @bralandealmeida fiz um novo deploy para mostrar o bug:
> 
> https://tabnews-git-fork-bralandealmeida-bugfix-adjust-c-6354bf-tabnews.vercel.app/login/sucesso
> 
> Estou alterando o PR para draft, ok? 🤝

Fiz a correção. Justamente nessa página não tinha feito a alteração do import. Tudo está ok agora. Também não tinha visto que já tinha retornado, por isso demorei para retornar aqui.

2022-12-22 11:29 UTC, bralandealmeida commented on pages/interface/components/Confetti/index.js
> +  useEffect(() => {
Acho que pode ser um caminho. Posso fazer essa alteração. 

Um ponto para observarmos é que, dessa forma, perdemos o listener do resize do browser e, consequentemente, em uma eventual alteração no tamanho da tela o confetti não irá se adaptar para o novo tamanho. Nesse caso, teríamos que passar essa lógica para os componentes que implementem essa feature do confetti... o que acha?

2022-12-22 12:57 UTC, aprendendofelipe commented on pages/interface/components/Confetti/index.js
> +  useEffect(() => {
Tinha pensado em eliminar o listener, pois ele só teria efeito se a janela fosse redimensionada enquanto os confetes estivessem caindo. Mas é melhor manter ele como você implementou, mesmo que esse caso seja uma exceção 👍

2022-12-22 12:59 UTC, bralandealmeida commented on pages/interface/components/Confetti/index.js
> +  useEffect(() => {
Eu pensei a mesma coisa. Imagino, no contexto da aplicação, são raras as exceções que as janelas vão ser redimensionadas. Mas pensei no uso de celulares e tablets, em que isso pode ser mais comum

2022-12-22 13:05 UTC, aprendendofelipe approved these changes

2022-12-22 13:55 UTC, aprendendofelipe commented
@bralandealmeida, como faz para reproduzir o problema original de overflow que você citou?

Agora está ocorrendo problema ao redimensionar a janela no mobile:

![image](https://user-images.githubusercontent.com/77860630/209149263-3f666a39-dd73-4ed0-ab12-c969e2f366e8.png)

2022-12-22 14:20 UTC, aprendendofelipe commented
> O comportamento original é exatamente o dessa evidência que você encaminhou. Ao fazer o login ou um post, por exemplo, quando chamamos pelo Confetti, ele gera um scroll para a direita da página

Ocorre em qual dispositivo e navegador?

2022-12-22 14:24 UTC, bralandealmeida commented
> > O comportamento original é exatamente o dessa evidência que você encaminhou. Ao fazer o login ou um post, por exemplo, quando chamamos pelo Confetti, ele gera um scroll para a direita da página
> 
> Ocorre em qual dispositivo e navegador?

Originalmente no desktop. Estou usando o Chrome.

2022-12-22 15:47 UTC, aprendendofelipe commented
@bralandealmeida, consegui reproduzir o problema original 👍

Sobre o novo problema, podemos resolver trocando `window.innerWidth` por `document.body.clientWidth`:

```js
setConfettiWidth(document.body.clientWidth);
```

Para o ajuste da altura é melhor manter o `window.innerHeight` mesmo.

Se concordar com essa alteração, basta subir ela pra eu aprovar o PR 🤝

2022-12-22 15:58 UTC, aprendendofelipe requested changes

2022-12-22 15:58 UTC, aprendendofelipe commented on pages/interface/components/Confetti/index.js
> +      setConfettiWidth(window.innerWidth);
```suggestion
      setConfettiWidth(document.body.clientWidth);
```

2022-12-22 15:59 UTC, bralandealmeida commented
> @bralandealmeida, consegui reproduzir o problema original 👍
> 
> Sobre o novo problema, podemos resolver trocando `window.innerWidth` por `document.body.clientWidth`:
> 
> ```js
> setConfettiWidth(document.body.clientWidth);
> ```
> 
> Para o ajuste da altura é melhor manter o `window.innerHeight` mesmo.
> 
> Se concordar com essa alteração, basta subir ela pra eu aprovar o PR 🤝

Claro, o que for melhor para o projeto 🤝

2022-12-29 12:42 UTC, bralandealmeida commented
Alteração enviada @aprendendofelipe

2023-01-03 11:33 UTC, aprendendofelipe approved these changes

2023-01-03 11:38 UTC, merged

2023-01-03 12:06 UTC, aprendendofelipe commented
Foi para produção 🚀