feat(gh-issues): Adicionando templates de Issues
filipedeschamps/tabnews.com.br pull request #892
Opened 2022-11-22 12:37 UTC by guilherssousa

Esse pull request adiciona dois Issue Templates do GitHub, feitos para ajudar os contribuidores a escrever issues mais completas e padronizadas, para evitar falta de detalhes ou fadiga visual por longos textos pouco sumarizados.

## Imagens
 Ao clicar para abrir uma issue, todos os templates disponíveis serão sugeridos para serem usados, além da opção de escrever uma issue em branco.
![image](https://user-images.githubusercontent.com/47110995/203315783-9690a8f6-2154-410c-ab17-77cd3d5ad437.png)

2022-11-22 16:30 UTC, aleixoporpino commented on .github/ISSUE_TEMPLATE/reporte-um-bug.md
> +about: Reporte um problema para nos ajudar a melhorear.
Pequeno typo `melhorar`

2022-11-22 16:34 UTC, guilherssousa commented on .github/ISSUE_TEMPLATE/reporte-um-bug.md
> +about: Reporte um problema para nos ajudar a melhorear.
Eita, nem percebi, vou corrigir! Obrigado!

2022-11-22 16:35 UTC, guilherssousa commented on .github/ISSUE_TEMPLATE/reporte-um-bug.md
> +about: Reporte um problema para nos ajudar a melhorear.
Corrigido!

2022-11-23 03:05 UTC, leonardodimarchi requested changes

2022-11-23 03:05 UTC, leonardodimarchi commented on .github/ISSUE_TEMPLATE/reporte-um-bug.md
> +**Comportamento esperado***
Um "*" a mais no "Comportamento esperado"

2022-11-23 13:45 UTC, r3nanp commented
Amazing job @guilherssousa!

2022-11-23 13:46 UTC, r3nanp approved these changes

2022-11-23 14:47 UTC, aleixoporpino approved these changes

2022-11-23 18:24 UTC, nicolasteofilo commented
bom trabalho, gostei bastante do template

2023-11-30 20:14 UTC, aprendendofelipe reviewed
Show de contribuição @guilherssousa, muito obrigado! 💪

Fiz algumas sugestões de alterações, mas também gostaria de saber sua opinião sobre a outra alternativa de template, que é usando [formulário](https://docs.github.com/pt/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) (`.yml` no lugar de `.md`).

Eu gosto do formulário porque podemos separar bem o que é ajuda para o preenchimento (e até o que deve ser verificado antes de abrir a issue) e o que é a informação que realmente precisamos que seja preenchida. Um bom exemplo é o [bug_report](https://github.com/vercel/next.js/issues/new?assignees=&labels=template%3A+bug&projects=&template=1.bug_report.yml) ou as [outras as opções](https://github.com/vercel/next.js/issues/new/choose) do Next.js.

Inclusive existe o PR #1005 do @yuric18 que usa essa outra alternativa.

Será muito bom se a Turma puder opinar sobre essas opções. 💪

2023-12-18 17:27 UTC, aprendendofelipe commented
@guilherssousa, vou fechar esse PR para focarmos no #1574, que implementou os templates usando `.yml` e está quase pronto. 🤝

Muito obrigado pela contribuição! 💪

2023-12-18 17:27 UTC, closed without merging