feat(login): show and hide password
filipedeschamps/tabnews.com.br pull request #926
Opened 2022-11-23 19:26 UTC by nicolasteofilo

2022-11-23 20:06 UTC, AugustoResende approved these changes
Parabéns pela PR!

2022-11-23 20:42 UTC, Rafatcb reviewed
Acredito que faz mais sentido criarmos um wrapper para o `TextInput` do `primer`, para poder reutilizar essa funcionalidade em outros lugares. Fora que, com isso, a atualização do status irá re-renderizar apenas o input, não a página inteira.

+1 sugestão: Seria interessante seguir a nomenclatura de variáveis booleanas, deixando o `is` no início (como já está em `isLoading`): 

```javascript
const [isPasswordVisible, setIsPasswordVisible] = useState(false);
```

2022-11-23 21:00 UTC, Rafatcb commented
> > Acredito que faz mais sentido criarmos um componente wrapper para o `TextInput` do `primer`, para poder reutilizar essa funcionalidade em outros lugares. Fora que, com isso, a atualização do status irá re-renderizar apenas o input, não a página inteira.
> 
> Pelo que vi ainda não existe esse conceito na aplicação.

O conceito de wrapper? Se for isso, acho que não tem problema, porque já existem duas páginas que podemos usar esse campo de senha: a de cadastro e de login.

Claro que é melhor aguardar o review de um contribuidor do repositório 👍

2022-11-23 21:14 UTC, aprendendofelipe commented
Boa @nicolasteofilo!

E faz sentido o que o @Rafatcb falou sobre o componente. Só não faz sentido ele não se considerar contribuidor depois de tantas contribuições 😅

2022-11-23 22:57 UTC, nicolasteofilo commented
Também acho legal o conceito do wrapper @Rafatcb, inclusive acho que vou fazer e não me esqueçi da página de cadastro inclusive né 🤣, vou dar um update e fazer isso, acho que podemos melhorar sim o componente para o Wrapper, mas poderia me explicar melhor como tu faria isso?

2022-11-23 22:58 UTC, nicolasteofilo commented
E vou dar o update também no nome da variável

2022-11-23 23:13 UTC, nicolasteofilo commented
cliquei duas vezes para pedir request de review, mal ai 🤣

2022-11-24 11:06 UTC, Rafatcb commented
Nunca cheguei a clonar ou estudar o repositório do TabNews, mas olhando por alto aqui, parece que temos uma pasta para colocar os componentes em [`pages/interface/components`](https://github.com/filipedeschamps/tabnews.com.br/tree/main/pages/interface/components).

Explicando a ideia do wrapper, seria criar um componente mais ou menos assim:

```jsx
export const PasswordInput= (props) => {
  const [isPasswordVisible, setIsPasswordVisible] = useState(false);

  function handleChangePasswordVisibility() {
    setIsPasswordVisible(prevState => !prevState);
  }

  return (
    <TextInput
      {...props}
      type={isPasswordVisible ? 'text' : 'password'}
      trailingAction={
        <TextInput.Action
          onClick={handleChangePasswordVisibility}
          icon={isPasswordVisible ? EyeIcon : EyeClosedIcon}
          aria-label={isPasswordVisible ? 'Ocultar senha' : 'Mostrar senha'}
        />
      }
    />
  );
};
```

Não sei se ter um componente só para input de senha é "demais", mas isso de fato simplifica o uso 👍

Nos meus projetos eu sempre crio um componente wrapper ao usar uma biblioteca, principalmente porque eu não uso Primer, Material UI etc, então preciso colocar meus estilos nos componentes, além de às vezes alterar algo do comportamento ou simplesmente facilitar o uso dele.

PS: Como eu disse que ainda não clonei o repo nenhuma vez, não vou conseguir testar a branch, já que está sem link de deploy também.

2022-11-24 14:30 UTC, nicolasteofilo commented
@Rafatcb Agora entendi o conceito... Acho que vou aplicar, e eu já avia visto em outros projetos coisas parecidas, ent acho que ficaria legal

2022-11-24 16:32 UTC, nicolasteofilo commented
Atualizações feitas, agora com o componente de Wrapper.

2022-11-24 19:04 UTC, leonardodimarchi requested changes

2022-11-24 19:04 UTC, leonardodimarchi commented on pages/login/index.public.js
> +  function handleChangePasswordVisibility() {
Me parece que faltou remover essa função "handleChangePasswordVisibility" da página de login

2022-11-24 20:37 UTC, aprendendofelipe commented
@nicolasteofilo, olhando só por cima, me parece que dá pra passar mais coisas para o componente que você criou.

2022-11-25 15:22 UTC, nicolasteofilo commented on pages/login/index.public.js
> +  function handleChangePasswordVisibility() {
Resolvido, mas achei estranho o husky com lint não ter pego isso 🤝

2022-11-25 15:27 UTC, nicolasteofilo commented
@aprendendofelipe Você tem razão, realmente tinha algumas coisas que dava para passar para o componente... Já passei agora 🤝

2022-11-25 21:47 UTC, leonardodimarchi approved these changes

2022-11-25 22:13 UTC, JonathanArgentao approved these changes

2022-12-08 20:40 UTC, aprendendofelipe commented
@nicolasteofilo, fiz umas sugestões no código, mas acrescento que esse componente também pode ser utilizado no arquivo `pages/cadastro/recuperar/[token].public.js`

Para facilitar a revisão, seria legal não fazer alterações que não tem nenhum efeito prático, principalmente em partes do código em que você não mexeu. Por exemplo a linha adicionada e a outra removida no arquivo `pages/cadastro/index.public.js`.

E se conseguir unificar os commits também seria legal 🤝

2022-12-21 21:12 UTC, aprendendofelipe requested changes
Oi @nicolasteofilo, fiz alguns comentários no código

2023-03-07 01:51 UTC, aprendendofelipe commented
@nicolasteofilo, muito obrigado por começar esse trabalho! 💪

O @edersonlucas concluiu ele no #1297 e já está em produção. 🚀

Por isso estou fechando esse PR. 👍

2023-03-07 01:51 UTC, closed without merging