feat(docs): reestilização do readme.md
filipedeschamps/tabnews.com.br pull request #947
Opened 2022-11-24 15:21 UTC by mavinsi

Adicionei um banner, badges das respectivas tecnologias usadas no projeto, além de emojis em cada categoria.

off: pull requeste totalmente estético kkkk

2022-11-24 16:25 UTC, Rafatcb commented on README.md
> +<img src="https://img.shields.io/badge/React-20232A?style=for-the-badge&logo=react&logoColor=61DAFB"> <img src="https://img.shields.io/badge/Tailwind_CSS-38B2AC?style=for-the-badge&logo=tailwind-css&
O banner ficou legal e acho que tudo bem ter os emojis nos tópicos, mas será que faz sentido mesmo ter as badges do que foi usado no desenvolvimento? Acho desnecessário, pode acabar ficando defasado e não importa tanto ter esse destaque para o que foi usado, porque a pessoa pode descobrir navegando pelo projeto e lendo o `package.json`.

Apesar disso, quero ver a opinião de outras pessoas aqui também 👍

2022-11-24 16:48 UTC, nicolasteofilo commented on README.md
> +<img src="https://img.shields.io/badge/React-20232A?style=for-the-badge&logo=react&logoColor=61DAFB"> <img src="https://img.shields.io/badge/Tailwind_CSS-38B2AC?style=for-the-badge&logo=tailwind-css&
Curti as mudanças, mas acho que nem vocẽ comentou, ficou um pouco poluido a parte dos badges, de resto ficou show 🚀

2022-11-24 17:13 UTC, lucasalberto01 commented on README.md
> +<img src="https://img.shields.io/badge/React-20232A?style=for-the-badge&logo=react&logoColor=61DAFB"> <img src="https://img.shields.io/badge/Tailwind_CSS-38B2AC?style=for-the-badge&logo=tailwind-css&
Outro ponto é que ele colou a logo do Tailwind... Porem o projeto não usa o Tailwind, ele usa o [prime](https://primer.style/react/)

2022-11-24 17:32 UTC, mavinsi commented on README.md
> +<img src="https://img.shields.io/badge/React-20232A?style=for-the-badge&logo=react&logoColor=61DAFB"> <img src="https://img.shields.io/badge/Tailwind_CSS-38B2AC?style=for-the-badge&logo=tailwind-css&
coloquei as badges das tecnologias que foram mostradas aqui 👉
https://github.com/filipedeschamps/tabnews.com.br/wiki/009.-Tecnologias

2022-11-24 23:04 UTC, Muurilo requested changes
A parte dos badges está muito poluída.

2022-11-25 03:28 UTC, alandev2 submitted a review, later dismissed

2022-11-25 03:28 UTC, alandev2 commented on README.md
> +## 👨‍💻 Rodar os testes
```suggestion
## 🧪 Rodar os testes
```

Dessa forma será que não ficaria mais interessante?

2022-11-25 17:45 UTC, jgbispo approved these changes

2022-11-26 10:32 UTC, Muurilo approved these changes

2022-11-26 23:09 UTC, jgbispo approved these changes

2023-10-06 18:29 UTC, closed without merging